name: Pylint-logi
run-name: Pylint-logi-${{github.run_number}}

on:
  pull_request:
    # workflow will run when a pull request is either created or moved from draft to ready,
    # or code is changed (synchronize)
    types: [ opened, ready_for_review,  synchronize]
    branches:
      - develop


jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" above.

    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Lint changed-files
    permissions:
      pull-requests: read
      contents: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check out PTB Repo
        uses: actions/checkout@v4
        with:
          clean: true
          
      - name: GitHub Information
        shell: bash
        run: |
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"
      - name: Install linting dependencies
        run: python -m pip install -r PYTESTBOX/TESTS/TOOLS/custom_linter/lint_requirements.txt

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo ${ALL_CHANGED_FILES}

      - name: Lint
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: python PYTESTBOX/TESTS/TOOLS/custom_linter/main.py -f ${ALL_CHANGED_FILES}

