// -------------------------------------
// Pipeline Configuration Section
properties([
    parameters([
        string(name: 'PROJECT_NAME', defaultValue: 'hadron', description: 'firmware hex file name', ),
        string(name: 'BRANCH_NAME', defaultValue: 'quark', description: 'project branch name on goldenpass', ),
        string(name: 'CODE_TAG', defaultValue: '', description: 'optional tag on goldenpass', ),
        string(name: 'CODE_PATCHSET', defaultValue: '', description: 'optional patchset on goldenpass', ),
        string(name: 'SOC_NAME', defaultValue: 'HADRON', description: 'System on a Chip definition', ),
        string(name: 'TEST_CONFIG', defaultValue: 'HADRON/PLATFORM', description: 'PRODUCT pyTestBox test configuration', ),
        string(name: 'ACTION_TYPES_TO_BUILD', defaultValue: '0 2 3',
            description: 'Action types values that will be used for -Dbtldr_ACTION_APP_TYPE to build extra hex files with the wanted action type for feature 0x00C3', ),
        string(name: 'PYTESTBOX_BRANCH_NAME', defaultValue: '*/develop',
            description: 'pyTestBox repo branch name', ),
    ]),
// End of Pipeline Configuration Section
// -------------------------------------
    pipelineTriggers([
        // Trigger on every update on master
        gerrit(
            serverName: 'goldenpass',
            gerritProjects: [[
                compareType: 'PLAIN',
                pattern: "ccp_fw/${params.BRANCH_NAME}",
                branches: [[ compareType: 'PLAIN', pattern: 'master' ]],
                disableStrictForbiddenFileVerification: false
            ]],
            silentMode: true,
            triggerOnEvents: [
                refUpdated(),
            ]
        )
    ]),
])

timestamps {

    node ('builder') {
        stage ('Build Job - Checkout') {
            if (env.GERRIT_CHANGE_SUBJECT && env.GERRIT_CHANGE_OWNER_NAME) {
                echo "ChangeLog: ${env.GERRIT_CHANGE_SUBJECT} from ${env.GERRIT_CHANGE_OWNER_NAME}"
            }
            if (env.GERRIT_REFSPEC) {
                ref_spec = env.GERRIT_REFSPEC
                branch_name = env.GERRIT_PATCHSET_REVISION
            }
            else
            {
                ref_spec = '+refs/heads/*:refs/remotes/origin/*'
                branch_name = '*/master'
            }
            echo "Refspec for checkout: ${ref_spec}"
            checkout([$class: 'GitSCM',
                branches: [[name: "${branch_name}"]], doGenerateSubmoduleConfigurations: false,
                extensions: [[ $class: 'CleanCheckout'],
                    [$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: false,
                    recursiveSubmodules: true, reference: '', trackingSubmodules: false
                ]],
                submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'Jenkins user',
                    url: "ssh://Jenkins@goldenpass.logitech.com:29418/ccp_fw/${params.BRANCH_NAME}",
                    refspec: "${ref_spec}"
                ]]
            ])
        } // End of stage ('Build Job - Checkout')

        stage ('Build Job - Build') {
            echo "PROJECT_NAME = ${params.PROJECT_NAME}"
            if (params.CODE_PATCHSET != '') {
              // Shell build step - sync on a patchset
              sh "git fetch ssh://Jenkins@goldenpass.logitech.com:29418/ccp_fw/quark refs/changes/${params.CODE_PATCHSET}"
              sh "git checkout FETCH_HEAD"
            } else {
              if (params.CODE_TAG != '') {
                // Shell build step - sync on a tag
                sh "git checkout tags/${params.CODE_TAG}"
              }
            }
            sh "git submodule update -i"
            sh "git clean -x -f"
            // Shell build step - Build production and test firmwares,
            //                    valid test dfu and phcs#1 v1.5 verification dfu files
            // Shell build step - Copy hard-coded Jenkins dfu key into dfu test key
            sh """
              cd gcc_eclipse
              make clean PROJECT=${params.PROJECT_NAME}
              make clean PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=build_ci
              cp ../config/priv_tstkey_jenkins.pem ../config/priv_tstkey.pem
              CPPFLAGS="-Dprot_BLEPRO_ENABLED=true" make -j8 BUILD_CONFIG=PROD PROJECT=${params.PROJECT_NAME}
              CPPFLAGS="-DCI_BUILD=1 -Dprot_BLEPRO_ENABLED=true" make -j8 PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=build_ci
              CPPFLAGS="-DCI_BUILD=1 -Dprot_BLEPRO_ENABLED=true" make -j8 BUILD_CONFIG=PROD PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=build_ci dfu_evt
              for i in ${params.ACTION_TYPES_TO_BUILD}; do
                  CPPFLAGS="-DCI_BUILD=1 -Dprot_BLEPRO_ENABLED=true -Dbtldr_ACTION_APP_TYPE=\${i} -Dbtldr_ACTION_BTLDR_TYPE=\${i}" make -j8 BUILD_CONFIG=PROD PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=action_type_\${i}
                  cd action_type_\${i}_${params.PROJECT_NAME}
                  hex_value=`printf \'%02X\' \${i}`
                  mv ${params.PROJECT_NAME}_prod.hex ../build_ci_${params.PROJECT_NAME}/${params.PROJECT_NAME}_prod_action_type_\${hex_value}.hex
                  cd ..
              done
            """
            // Build and get DFU of first action type of the ACTION_TYPES_TO_BUILD list
            sh """
              cd gcc_eclipse
              make clean PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=action_type_app_${params.ACTION_TYPES_TO_BUILD[0]}
              cd ../config
              cp priv_tstkey_jenkins.pem priv_tstkey.pem
              cd ../gcc_eclipse
              CPPFLAGS="-DCI_BUILD=1 -Dprot_BLEPRO_ENABLED=true -Dbtldr_ACTION_APP_TYPE=${params.ACTION_TYPES_TO_BUILD[0]}" make -j8 BUILD_CONFIG=PROD PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=action_type_app_${params.ACTION_TYPES_TO_BUILD[0]} dfu_evt
              cd action_type_app_${params.ACTION_TYPES_TO_BUILD[0]}_${params.PROJECT_NAME}
              mv ${params.PROJECT_NAME}_prod.hex ../build_ci_${params.PROJECT_NAME}/${params.PROJECT_NAME}_prod_action_type_app_${params.ACTION_TYPES_TO_BUILD[0]}.hex
              cd dfu_evt_prod
              mv good.dfu ../../build_ci_${params.PROJECT_NAME}/${params.PROJECT_NAME}_prod_action_type_app_${params.ACTION_TYPES_TO_BUILD[0]}.dfu
              cd ../..
            """
            sh(returnStdout: true, script: '''#!/bin/bash
              if [ ! -z "$(git status --porcelain)" ]; then
                echo "Uncommitted changes in tracked files"
                echo "$(git status --porcelain)"
                exit 1
              fi
            '''.stripIndent())
            archiveArtifacts allowEmptyArchive: false,
                             artifacts: """**gcc_eclipse/**/*.dfu,
                                           **gcc_eclipse/build_*/${params.PROJECT_NAME}*.hex,
                                           **gcc_eclipse/build_ci_*prod/${params.PROJECT_NAME}*.elf,
                                           **/dfu_*_key.txt,
                                           **/priv_tstkey_jenkins.pem,
                                           **gcc_eclipse/build_ci_*prod/*.map""",
                             caseSensitive: true,
                             defaultExcludes: true,
                             fingerprint: false,
                             onlyIfSuccessful: false
            // Clean workspace at build end
            cleanWs()
        } // End of stage ('Build Job - Build')
    } // End of node ('builder')

    node ('fw_check') {

        stage ('Firmwares Comparison Job - Checkout') {
            checkout([$class: 'GitSCM',
                branches: [[name: "${params.PYTESTBOX_BRANCH_NAME}"]], doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']], submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'GithubProductsCIToken', url: "https://github.com/Logitech/py-test-box.git"]]
            ])
        } // End of stage ('Firmwares Comparison Job - Checkout')

        stage ('Firmwares Comparison Job - Build') {
            script {
                copyArtifacts(
                    filter: """**gcc_eclipse/build_*/${params.PROJECT_NAME}_prod.hex,
                               **gcc_eclipse/build_ci_*prod/${params.PROJECT_NAME}*.elf""",
                    projectName: env.JOB_NAME,
                    fingerprintArtifacts: true,
                    selector: specific(env.BUILD_NUMBER),
                    target: 'PYTESTBOX/TESTS/DFU_FILES'
                )

                try {
                    // Shell Unit Test step - framework initialization
                    sh """
                      python3 PYTESTBOX/LIBS/PYSETUP/pyEnvChecker.py
                    """
                    // Shell Unit Test step - production vs test firmwares comparison
                    def path = 'PYTESTBOX/TESTS/DFU_FILES/gcc_eclipse/build_'
                    sh """
                      python3 PYTESTBOX/CICD/ciscripts/compare_hex.py  \
                          -f ${path}${params.PROJECT_NAME}/${params.PROJECT_NAME}_prod.hex  \
                          -c ${path}ci_${params.PROJECT_NAME}/${params.PROJECT_NAME}_prod.hex \
                          -b ${path}ci_${params.PROJECT_NAME}_btldr_prod/${params.PROJECT_NAME}_btldr.elf \
                          -e ${path}ci_${params.PROJECT_NAME}_app_prod/${params.PROJECT_NAME}_app.elf
                    """
                }
                finally {
                    try {
                        // Permission cleanup
                        sh "python3 PYTESTBOX/CICD/ciscripts/permissions_clean_up.py"
                    }
                    catch(all) {
                        echo 'Error cleaning up permissions'
                    }
                }
            }
        } // End of stage ('Firmwares Comparison Job - Build')
    } // End of node ('slave')
} // End of timestamps