#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Python Test Box
# ----------------------------------------------------------------------------
"""
:package: pyhid.hid.controlidtable
:brief: Description of the HID usage for a control.
    https://sites.google.com/a/logitech.com/samarkand/appendix/control-id-table
:author: Christophe Roquebert <croquebert@logitech.com>
:date: 2020/03/09
"""
# ----------------------------------------------------------------------------
# imports
# ----------------------------------------------------------------------------
from enum import IntEnum

from pylibrary.emulator.keyid import KEY_ID


# ------------------------------------------------------------------------------
# Implementation
# ------------------------------------------------------------------------------
class CidTable(IntEnum):
    """
    Control ID : This is the 16bit value which identifies the control in the list
    reported by keyboard or mice for a control assignment.

    The list below has been completed from the C&P guidelines document
    https://docs.google.com/spreadsheets/d/1f066R9V1WS2B9Ebh9_8tvdEAXs39QA2BnQbnTBNNvgU/edit#gid=44851045

    Control ID definition
    https://samarkand.logitech.com/samarkand/latest/protocol_specs/control_id_table.html

    Control ID definition for FKC feature
    https://docs.google.com/spreadsheets/d/1rY01b28rLEhpvsTUykMTK9KN2khjRY9L_ZD1_6oyMpI
    """
    # Special
    NONE = 0x0000

    # Mouse
    LEFT_CLICK = 0x0050
    RIGHT_CLICK = 0x0051
    MIDDLE_BUTTON = 0x0052
    BACK = 0x0053
    AC_BACK = 0x0054
    BACK_WIN = 0x0055
    FORWARD = 0x0056
    AC_FORWARD = 0x0057
    FORWARD_WIN = 0x0058
    BUTTON_6 = 0x0059
    BUTTON_7 = 0x005A
    LEFT_SCROLL = 0x005B
    BUTTON_8 = 0x005C
    RIGHT_SCROLL = 0x005D
    BUTTON_9 = 0x005E
    BUTTON_10 = 0x005F
    BUTTON_11 = 0x0060
    BUTTON_12 = 0x0061
    BUTTON_13 = 0x0062
    BUTTON_14 = 0x0063
    BUTTON_15 = 0x0064
    BUTTON_16 = 0x0065
    BUTTON_17 = 0x0066
    BUTTON_18 = 0x0067
    BUTTON_19 = 0x0068
    BUTTON_20 = 0x0069
    BUTTON_21 = 0x006A
    BUTTON_22 = 0x006B
    BUTTON_23 = 0x006C
    BUTTON_24 = 0x006D
    APP_SWITCH_GESTURE = 0x00C3
    SMART_SHIFT = 0x00C4
    VIRTUAL_GESTURE_BUTTON = 0x00D7
    DPI_CHANGE = 0x00ED
    DPI_SWITCH = 0x00FD

    # Keyboard
    NON_RE_PROGRAMMABLE_VOLUME_UP = 0x0001
    NON_RE_PROGRAMMABLE_VOLUME_DOWN = 0x0002
    NON_RE_PROGRAMMABLE_MUTE = 0x0003
    NON_RE_PROGRAMMABLE_PLAY_PAUSE = 0x0004
    NON_RE_PROGRAMMABLE_NEXT = 0x0005
    NON_RE_PROGRAMMABLE_PREVIOUS = 0x0006
    STOP = 0x0007
    DOCUMENT_FLIP = 0x0008
    BURN = 0x0009
    CALCULATOR = 0x000A
    CALENDAR = 0x000B
    CLOSE = 0x000C
    EJECT = 0x000D
    HELP = 0x000F
    HELP_F1 = 0x0010
    LAUNCH_WORD = 0x0011
    LAUNCH_SPREADSHEET = 0x0012
    LAUNCH_PRESENTATION = 0x0013
    UNDO = 0x0014
    UNDO_F5 = 0x0015
    REDO = 0x0016
    REDO_F6 = 0x0017
    PRINT = 0x0018
    PRINT_F7 = 0x0019
    SAVE = 0x001A
    SAVE_F8 = 0x001B
    PRESET_A = 0x001C
    PRESET_B = 0x001D
    PRESET_C = 0x001E
    PRESET_D = 0x001F
    FAVORITES = 0x0020
    GADGETS_ICO = 0x0021
    MY_HOME = 0x0022
    GADGETS_WIN = 0x0023
    MAXIMIZE = 0x0024
    MAXIMIZE_WIN = 0x0025
    MINIMIZE = 0x0026
    MINIMIZE_WIN = 0x0027
    MEDIA_PLAYER = 0x0028
    MEDIA_CENTER = 0x0029
    MEDIA_CENTER_WIN = 0x002A   # DO NOT USE
    SHOW_CUSTOM_MENU = 0x002B
    MESSENGER = 0x002C
    MY_DOCUMENT = 0x002D
    MY_MUSIC = 0x002E
    WEBCAM = 0x002F
    MY_PICTURES = 0x0030
    MY_VIDEO = 0x0031
    MY_COMPUTER = 0x0032
    MY_COMPUTER_WIN = 0x0033
    FN_KEY = 0x0034
    PICTURE_APPLICATION = 0x0035
    ONE_TOUCH_SEARCH = 0x0036
    MY_FAVORITES_PRESET_1 = 0x0037
    MY_FAVORITES_PRESET_2 = 0x0038
    MY_FAVORITES_PRESET_3 = 0x0039
    MY_FAVORITES_PRESET_4 = 0x003A
    RECORD = 0x003B
    INTERNET_REFRESH = 0x003C
    ROTATE = 0x003D
    SEARCH = 0x003E
    SHUFFLE = 0x003F
    SLEEP = 0x0040
    INTERNET_STOP = 0x0041
    SYNCHRONIZE = 0x0042
    ZOOM = 0x0043
    AC_ZOOM_IN = 0x0044
    ZOOM_IN_WIN = 0x0045
    ZOOM_IN = 0x0046
    AC_ZOOM_OUT = 0x0047
    ZOOM_OUT_WIN = 0x0048
    ZOOM_OUT = 0x0049
    ZOOM_RESET = 0x004A
    ZOOM_FULL_SCREEN = 0x004B
    PRINT_SCREEN = 0x004C
    PAUSE_BREAK = 0x004D
    SCROLL_LOCK = 0x004E
    CONTEXTUAL_MENU = 0x004F
    SHOW_DESKTOP = 0x006E
    LOCK_COMPUTER = 0x006F
    FN_F1 = 0x0070
    FN_F2 = 0x0071
    FN_F3 = 0x0072
    FN_F4 = 0x0073
    FN_F5 = 0x0074
    FN_F6 = 0x0075
    FN_F7 = 0x0076
    FN_F8 = 0x0077
    FN_F9 = 0x0078
    FN_F10 = 0x0079
    FN_F11 = 0x007A
    FN_F12 = 0x007B
    FN_F13 = 0x007C
    FN_F14 = 0x007D
    FN_F15 = 0x007E
    FN_F16 = 0x007F
    FN_F17 = 0x0080
    FN_F18 = 0x0081
    FN_F19 = 0x0082
    HOME_IOS = 0x0083
    HOME_ANDROID = 0x0084
    MENU_MOBILE = 0x0085
    SEARCH_MOBILE = 0x0086
    BACK_ANDROID = 0x0087
    HOME_MOBILE = 0x0088
    LOCK_MOBILE = 0x0089
    VIRTUAL_KEYBOARD_IOS = 0x008A
    SWITCH_LANGUAGE_IOS = 0x008B
    EXPOSE_MAC = 0x008C
    DASHBOARD_MAC = 0x008D
    SNAP_LEFT_WIN7 = 0x008E
    SNAP_RIGHT_WIN7 = 0x008F
    MINIMIZE_RESTORE_WIN7 = 0x0090
    MAXIMIZE_RESTORE_WIN7 = 0x0091
    STRETCH_UP_WIN7 = 0x0092
    SWITCH_MONITOR_PLUS_WIN7 = 0x0093
    SWITCH_MONITOR_MINUS_WIN7 = 0x0094
    SHOW_PRESENTATION_MODE_WIN7 = 0x0095
    SHOW_MOBILITY_CENTER_WIN7 = 0x0096
    ANALOG_HORIZONTAL_SCROLL = 0x0097
    MISSION_CONTROL = 0x0098
    LAUNCH_PAD_MAC = 0x0099
    BRIGHTNESS_DOWN_MAC = 0x009A
    BRIGHTNESS_UP_MAC = 0x009B
    LOCK_IOS = 0x009C
    PRINT_SCREEN_SCROLL_LOCK = 0x009D
    DELETE_INSERT = 0x009E
    METRO_APP_SWITCH_1 = 0x009F
    METRO_APP_BAR = 0x00A0
    METRO_CHARMS = 0x00A1
    EJECT_VIRTUAL_KBD_CALCULATOR = 0x00A2
    METRO_SEARCH_FILES = 0x00A3
    SLEEP_MOBILE = 0x00A4
    SHARE_WIN8 = 0x00A5
    SETTINGS_WIN8 = 0x00A6
    DEVICES_WIN8 = 0x00A7
    MENU_WIN_ANDROID = 0x00A8
    METRO_START_WIN = 0x00A9
    DOUBLE_TAP_FRONT = 0x00AA
    DOUBLE_TAP_BACK = 0x00AB
    FINGER_DOWN = 0x00AC
    REPORTED_FN = 0x00AD
    NEW_SHOW_DESKTOP = 0x00AE
    WIN8_SPECIAL_KEY = 0x00AF
    METRO_START = 0x00B0
    SEARCH_CHARM_LS = 0x00B1
    SEARCH_CHARM_LA = 0x00B2
    SHARE_CHARM = 0x00B3
    DEVICES_CHARM = 0x00B4
    SETTINGS_CHARM = 0x00B5
    APP_SWITCH_2 = 0x00B6
    FN_LEFT_CLICK = 0x00B7
    SECOND_LEFT_CLICK = 0x00B8
    FN_SECOND_LEFT_CLICK = 0x00B9
    APP_SWITCH_MISSION_CONTROL = 0x00BA
    MULTI_PLATFORM_HOME = 0x00BB
    MENU = 0x00BC
    MULTI_PLATFORM_AC_BACK = 0x00BD
    MULTI_PLATFORM_INSERT = 0x00BE
    SCREEN_CAPTURE_PRINT_SCREEN = 0x00BF
    FN_DOWN = 0x00C0    # Deprecated
    FN_UP = 0x00C1      # Deprecated
    LOCK = 0x00C2
    MICROPHONE = 0x00C5
    WIFI = 0x00C6
    BRIGHTNESS_DOWN = 0x00C7
    BRIGHTNESS_UP = 0x00C8
    DISPLAY_OUT = 0x00C9
    VIEW_OPEN_APPS = 0x00CA
    VIEW_ALL_APPS = 0x00CB
    SWITCH_APP = 0x00CC
    FN_INVERSION_CHANGE = 0x00CD
    MULTI_PLATFORM_BACK = 0x00CE
    MULTI_PLATFORM_FORWARD = 0x00CF
    GESTURE_BUTTON = 0x00D0
    HOST_SWITCH_1 = 0x00D1
    HOST_SWITCH_2 = 0x00D2
    HOST_SWITCH_3 = 0x00D3
    MULTI_PLATFORM_SEARCH = 0x00D4
    HOME_MISSION_CONTROL = 0x00D5
    MENU_LAUNCHPAD = 0x00D6
    CURSOR_BUTTON_LONG_PRESS = 0x00D8
    NEXT_BUTTON = 0x00D9
    NEXT_BUTTON_LONG_PRESS = 0x00DA
    BACK_BUTTON = 0x00DB
    BACK_BUTTON_LONG_PRESS = 0x00DC
    LANGUAGE_SWITCH = 0x00DD
    FN_LOCK = 0x00DE
    SWITCH_HIGHLIGHT = 0x00DF
    MISSION_CTRL_TASK_VIEW = 0x00E0
    LAUNCHPAD_ACTION_CENTER = 0x00E1
    BACKLIGHT_DOWN = 0x00E2
    BACKLIGHT_UP = 0x00E3
    PREV_TRACK = 0x00E4
    PLAY_PAUSE = 0x00E5
    NEXT_TRACK = 0x00E6
    MUTE = 0x00E7
    VOLUME_DOWN = 0x00E8
    VOLUME_UP = 0x00E9
    CONTEXTUAL_MENU_RIGHT_CLICK = 0x00EA
    RIGHT_ARROW = 0x00EB
    LEFT_ARROW = 0x00EC
    NEW_TAB = 0x00EE
    F2 = 0x00EF
    F3 = 0x00F0
    F4 = 0x00F1
    F5 = 0x00F2
    F6 = 0x00F3
    F7 = 0x00F4
    F8 = 0x00F5
    F1 = 0x00F6
    NEXT_COLOR_EFFECT = 0x00F7
    INCREASE_COLOR_EFFECT_SPEED = 0x00F8
    DECREASE_COLOR_EFFECT_SPEED = 0x00F9
    LOAD_LIGHTING_CUSTOM_EFFECT = 0x00FA
    LASER_BUTTON_SHORT_PRESS = 0x00FB
    LASER_BUTTON_LONG_PRESS = 0x00FC
    HOME_SHOW_DESKTOP = 0x00FE
    APP_SWITCH_SHOW_DASHBOARD = 0x00FF
    APP_SWITCH = 0x0100
    FN_INVERSION = 0x0101
    LEFT_RIGHT_CLICK = 0x0102
    VOICE_DICTATION = 0x0103
    SMILING_FACE_WITH_HEART_SHAPED_EYES = 0x0104
    LOUDLY_CRYING_FACE = 0x0105
    EMOJI_SMILEY = 0x0106
    EMOJI_SMILEY_WITH_TEARS = 0x0107
    EMOJI_PANEL = 0x0108
    APP_SWITCH_LAUNCHPAD = 0x0109
    SNIPPING_TOOL = 0x010A
    GRAVE_ACCENT = 0x010B
    TAB = 0x010C
    CAPS_LOCK = 0x010D
    LEFT_SHIFT = 0x010E
    LEFT_CTRL = 0x010F
    LEFT_OPTION_START = 0x0110
    LEFT_CMD_ALT = 0x0111
    RIGHT_CMD_ALT = 0x0112
    RIGHT_OPTION_START = 0x0113
    RIGHT_CTRL = 0x0114
    RIGHT_SHIFT = 0x0115
    INSERT = 0x0116
    DELETE = 0x0117
    HOME = 0x0118
    END = 0x0119
    PAGE_UP = 0x011A
    PAGE_DOWN = 0x011B
    MUTE_MICROPHONE = 0x011C
    DO_NOT_DISTURB = 0x011D
    BACKSLASH = 0x011E
    REFRESH = 0x011F
    CLOSE_TAB = 0x0120
    LANG_SWITCH = 0x0121
    STANDARD_KEY_A = 0x0122
    STANDARD_KEY_B = 0x0123
    STANDARD_KEY_C = 0x0124
    STANDARD_KEY_D = 0x0125
    STANDARD_KEY_E = 0x0126
    STANDARD_KEY_F = 0x0127
    STANDARD_KEY_G = 0x0128
    STANDARD_KEY_H = 0x0129
    STANDARD_KEY_I = 0x012A
    STANDARD_KEY_J = 0x012B
    STANDARD_KEY_K = 0x012C
    STANDARD_KEY_L = 0x012D
    STANDARD_KEY_M = 0x012E
    STANDARD_KEY_N = 0x012F
    STANDARD_KEY_O = 0x0130
    STANDARD_KEY_P = 0x0131
    STANDARD_KEY_Q = 0x0132
    STANDARD_KEY_R = 0x0133
    STANDARD_KEY_S = 0x0134
    STANDARD_KEY_T = 0x0135
    STANDARD_KEY_U = 0x0136
    STANDARD_KEY_V = 0x0137
    STANDARD_KEY_W = 0x0138
    STANDARD_KEY_X = 0x0139
    STANDARD_KEY_Y = 0x013A
    STANDARD_KEY_Z = 0x013B
    LEFT_OPTION = 0x013D
    RIGHT_OPTION = 0x013E
    LEFT_COMMAND = 0x013F
    RIGHT_COMMAND = 0x0140
    PLAY_PAUSE_DOUBLE_TRACK = 0x0141
    STANDARD_0 = 0x0142
    STANDARD_1 = 0x0143
    STANDARD_2 = 0x0144
    STANDARD_3 = 0x0145
    STANDARD_4 = 0x0146
    STANDARD_5 = 0x0147
    STANDARD_6 = 0x0148
    STANDARD_7 = 0x0149
    STANDARD_8 = 0x014A
    STANDARD_9 = 0x014B
    STANDARD_ESC = 0x014C
    F9 = 0x014D
    F10 = 0x014E
    F11 = 0x014F
    F12 = 0x0150
    STANDARD_UP_ARROW = 0x0151
    STANDARD_DOWN_ARROW = 0x0152
    STANDARD_EQUAL_AND_PLUS = 0x0153
    STANDARD_FN = 0x0154
    STANDARD_ENTER = 0x0155
    STANDARD_BACKSPACE = 0x0156
    STANDARD_DASH_AND_UNDERSCORE = 0x0158
    BLUETOOTH = 0x0159
    STANDARD_LEFT_BRACKET_AND_BRACE = 0x015A
    STANDARD_RIGHT_BRACKET_AND_BRACE = 0x015B
    STANDARD_SEMICOLON_AND_COLON = 0x015C
    STANDARD_APOSTROPHE_AND_QUOTATION_MARK = 0x015D
    STANDARD_FORWARD_SLASH_AND_QUESTION_MARK = 0x015E
    STANDARD_PERIOD_AND_MORE = 0x015F
    STANDARD_COMMA_AND_LESS = 0x0160
    STANDARD_SPACE_BAR = 0x0161
    F13 = 0x0162
    F14 = 0x0163
    F15 = 0x0164
    F16 = 0x0165
    F17 = 0x0166
    F18 = 0x0167
    F19 = 0x0168
    NON_US_AND_TILDE = 0x0169
    NON_US_BACKSLASH_AND_PIPE = 0x016A
    NUMPAD_NUM_LOCK_AND_CLEAR = 0x016B
    NUMPAD_SLASH = 0x016C
    NUMPAD_ASTERISK = 0x016D
    NUMPAD_MINUS = 0x016E
    NUMPAD_PLUS = 0x016F
    NUMPAD_ENTER = 0x170
    NUMPAD_1_AND_END = 0x0171
    NUMPAD_2_AND_DOWN_ARROW = 0x0172
    NUMPAD_3_AND_PAGE_DOWN = 0x0173
    NUMPAD_4_AND_LEFT_ARROW = 0x0174
    NUMPAD_5 = 0x0175
    NUMPAD_6_AND_RIGHT_ARROW = 0x0176
    NUMPAD_7_AND_HOME = 0x0177
    NUMPAD_8_AND_UP_ARROW = 0x0178
    NUMPAD_9_AND_PAGE_UP = 0x0179
    NUMPAD_0_AND_INSERT = 0x017A
    NUMPAD_FULL_STOP_AND_DELETE = 0x017B
    INTERNATIONAL1 = 0x017C
    RO = 0x017C
    INTERNATIONAL2 = 0x017D
    KATAHIRA = 0x017D
    INTERNATIONAL3 = 0x017E
    YEN = 0x017E
    INTERNATIONAL4 = 0x017F
    HENKAN = 0x017F
    INTERNATIONAL5 = 0x0180
    MUHENKAN = 0x0180
    LANG3 = 0x0181
    LANG4 = 0x0182
    LS2_BLE_CONNECTION_TOGGLE = 0x0183
    KEY_BRIGHTNESS_CYCLE = 0x0184
    GAME_MODE_BTN = 0x0185
    ROLLER0_SCROLL_UP = 0x0186
    ROLLER0_SCROLL_DOWN = 0x0187
    ROLLER1_SCROLL_UP = 0x0188
    ROLLER1_SCROLL_DOWN = 0x0189
    LS2_BTN = 0x018A
    LEFT_ALT = 0x018B
    LEFT_GUI = 0x018C
    RIGHT_ALT = 0x018D
    RIGHT_GUI = 0x018E
    G_KEY1 = 0x018F
    G_KEY2 = 0x0190
    G_KEY3 = 0x0191
    G_KEY4 = 0x0192
    G_KEY5 = 0x0193
    G_KEY6 = 0x0194
    G_KEY7 = 0x0195
    G_KEY8 = 0x0196
    G_KEY9 = 0x0197
    DIDOT_VIRTUAL_BUTTON1 = 0x0198
    DIDOT_VIRTUAL_BUTTON2 = 0x0199
    DIDOT_VIRTUAL_BUTTON3 = 0x019A
    DIDOT_VIRTUAL_BUTTON4 = 0x019B
    DIDOT_VIRTUAL_BUTTON5 = 0x019C
    DIDOT_VIRTUAL_BUTTON6 = 0x019D
    DIDOT_VIRTUAL_BUTTON7 = 0x019E
    DIDOT_VIRTUAL_BUTTON8 = 0x019F
    LAUNCH_DIDOT = 0x01A0
    LEFT_PROFILE_ARROW = 0x01A1
    RIGHT_PROFILE_ARROW = 0x01A2
    # PWS Keyboard Keys Guidelines v3.1
    SMART_ACTION_1 = 0x01A3
    SMART_ACTION_2 = 0x01A4
    SMART_ACTION_3 = 0x01A5
    SMART_ACTION_4 = 0x01A6
    BACKLIGHT_CYCLING = 0x01A7
# end class CidTable


CID_TO_KEY_ID_MAP = {

    CidTable.LEFT_CLICK:                KEY_ID.LEFT_BUTTON,
    CidTable.RIGHT_CLICK:               KEY_ID.RIGHT_BUTTON,
    CidTable.MIDDLE_BUTTON:             KEY_ID.MIDDLE_BUTTON,
    CidTable.BACK:                      KEY_ID.BACK_BUTTON,
    CidTable.FORWARD:                   KEY_ID.FORWARD_BUTTON,
    CidTable.BUTTON_7:                  KEY_ID.BUTTON_7,
    CidTable.LEFT_SCROLL:               KEY_ID.LEFT_SCROLL,
    CidTable.BUTTON_8:                  KEY_ID.BUTTON_8,
    CidTable.RIGHT_SCROLL:              KEY_ID.RIGHT_SCROLL,
    CidTable.BUTTON_9:                  KEY_ID.BUTTON_9,
    CidTable.APP_SWITCH_GESTURE:        KEY_ID.APP_SWITCH_GESTURE,
    CidTable.SMART_SHIFT:               KEY_ID.SMART_SHIFT,
    CidTable.VIRTUAL_GESTURE_BUTTON:    KEY_ID.VIRTUAL_GESTURE_BUTTON,
    CidTable.DPI_CHANGE:                KEY_ID.DPI_CHANGE,
    CidTable.DPI_SWITCH:                KEY_ID.DPI_SWITCH,

    CidTable.FN_LOCK:                       KEY_ID.FN_LOCK,
    CidTable.FN_INVERSION:                  KEY_ID.FN_INVERSION,
    CidTable.BRIGHTNESS_DOWN:               KEY_ID.BRIGHTNESS_DOWN,
    CidTable.BRIGHTNESS_UP:                 KEY_ID.BRIGHTNESS_UP,
    CidTable.MISSION_CTRL_TASK_VIEW:        KEY_ID.MISSION_CTRL_TASK_VIEW,
    CidTable.LAUNCHPAD_ACTION_CENTER:       KEY_ID.LAUNCHPAD_ACTION_CENTER,
    CidTable.SHOW_DESKTOP:                  KEY_ID.SHOW_DESKTOP,
    CidTable.BACKLIGHT_DOWN:                KEY_ID.BACKLIGHT_DOWN,
    CidTable.BACKLIGHT_UP:                  KEY_ID.BACKLIGHT_UP,
    CidTable.PREV_TRACK:                    KEY_ID.PREV_TRACK,
    CidTable.PLAY_PAUSE:                    KEY_ID.PLAY_PAUSE,
    CidTable.NEXT_TRACK:                    KEY_ID.NEXT_TRACK,
    CidTable.STOP:                          KEY_ID.KEYBOARD_STOP,
    CidTable.MUTE:                          KEY_ID.KEYBOARD_MUTE,
    CidTable.VOLUME_DOWN:                   KEY_ID.KEYBOARD_VOLUME_DOWN,
    CidTable.VOLUME_UP:                     KEY_ID.KEYBOARD_VOLUME_UP,
    CidTable.HOST_SWITCH_1:                 KEY_ID.HOST_1,
    CidTable.HOST_SWITCH_2:                 KEY_ID.HOST_2,
    CidTable.HOST_SWITCH_3:                 KEY_ID.HOST_3,
    CidTable.CALCULATOR:                    KEY_ID.CALCULATOR,
    CidTable.EJECT:                         KEY_ID.EJECT,
    CidTable.SCREEN_CAPTURE_PRINT_SCREEN:   KEY_ID.KEYBOARD_PRINT_SCREEN,
    CidTable.SNIPPING_TOOL:                 KEY_ID.SCREEN_CAPTURE,
    CidTable.VOICE_DICTATION:               KEY_ID.DICTATION,
    CidTable.CONTEXTUAL_MENU_RIGHT_CLICK:   KEY_ID.CONTEXTUAL_MENU,
    CidTable.LOCK_COMPUTER:                 KEY_ID.SCREEN_LOCK,
    CidTable.LEFT_ARROW:                    KEY_ID.KEYBOARD_LEFT_ARROW,
    CidTable.RIGHT_ARROW:                   KEY_ID.KEYBOARD_RIGHT_ARROW,
    CidTable.STANDARD_UP_ARROW:             KEY_ID.KEYBOARD_UP_ARROW,
    CidTable.STANDARD_DOWN_ARROW:           KEY_ID.KEYBOARD_DOWN_ARROW,
    CidTable.FN_KEY:                        KEY_ID.FN_KEY,
    CidTable.FN_INVERSION_CHANGE:           KEY_ID.FN_INVERSION_CHANGE,
    CidTable.MULTI_PLATFORM_SEARCH:         KEY_ID.MULTI_PLATF_SEARCH_SPOTLIGHT,
    CidTable.MULTI_PLATFORM_BACK:           KEY_ID.MULTI_PLATF_BACK,
    CidTable.APP_SWITCH:                    KEY_ID.APP_SWITCH,
    CidTable.APP_SWITCH_LAUNCHPAD:          KEY_ID.APP_SWITCH_LAUNCHPAD,
    CidTable.MUTE_MICROPHONE:               KEY_ID.MUTE_MICROPHONE,
    CidTable.LANGUAGE_SWITCH:               KEY_ID.LANGUAGE_SWITCH,
    CidTable.INSERT:                        KEY_ID.KEYBOARD_INSERT,
    CidTable.DELETE:                        KEY_ID.KEYBOARD_DELETE_FORWARD,
    CidTable.HOME:                          KEY_ID.KEYBOARD_HOME,
    CidTable.END:                           KEY_ID.KEYBOARD_END,
    CidTable.PAGE_UP:                       KEY_ID.KEYBOARD_PAGE_UP,
    CidTable.PAGE_DOWN:                     KEY_ID.KEYBOARD_PAGE_DOWN,
    CidTable.SMILING_FACE_WITH_HEART_SHAPED_EYES: KEY_ID.SMILING_FACE_WITH_HEART_SHAPED_EYES,
    CidTable.LOUDLY_CRYING_FACE:        KEY_ID.LOUDLY_CRYING_FACE,
    CidTable.EMOJI_SMILEY:              KEY_ID.EMOJI_SMILEY,
    CidTable.EMOJI_SMILEY_WITH_TEARS:   KEY_ID.EMOJI_SMILEY_WITH_TEARS,
    CidTable.EMOJI_PANEL:               KEY_ID.EMOJI_PANEL,
    CidTable.GRAVE_ACCENT:              KEY_ID.KEYBOARD_GRAVE_ACCENT_AND_TILDE,
    CidTable.TAB:                       KEY_ID.KEYBOARD_TAB,
    CidTable.CAPS_LOCK:                 KEY_ID.KEYBOARD_CAPS_LOCK,
    CidTable.LEFT_SHIFT:                KEY_ID.KEYBOARD_LEFT_SHIFT,
    CidTable.LEFT_CTRL:                 KEY_ID.KEYBOARD_LEFT_CONTROL,
    CidTable.LEFT_OPTION_START:         KEY_ID.KEYBOARD_LEFT_WIN_OR_OPTION,
    CidTable.LEFT_CMD_ALT:              KEY_ID.KEYBOARD_LEFT_ALT,
    CidTable.RIGHT_CMD_ALT:             KEY_ID.KEYBOARD_RIGHT_ALT,
    CidTable.RIGHT_OPTION_START:        KEY_ID.KEYBOARD_RIGHT_WIN_OR_OPTION,
    CidTable.RIGHT_CTRL:                KEY_ID.KEYBOARD_RIGHT_CONTROL,
    CidTable.RIGHT_SHIFT:               KEY_ID.KEYBOARD_RIGHT_SHIFT,
    CidTable.DO_NOT_DISTURB:            KEY_ID.DO_NOT_DISTURB,
    CidTable.BACKSLASH:                 KEY_ID.KEYBOARD_BACKSLASH_AND_PIPE,
    CidTable.LEFT_OPTION:               KEY_ID.KEYBOARD_LEFT_WIN_OR_OPTION,
    CidTable.RIGHT_OPTION:              KEY_ID.KEYBOARD_RIGHT_WIN_OR_OPTION,
    CidTable.LEFT_COMMAND:              KEY_ID.KEYBOARD_LEFT_ALT,
    CidTable.RIGHT_COMMAND:             KEY_ID.KEYBOARD_RIGHT_ALT,
    CidTable.PLAY_PAUSE_DOUBLE_TRACK:   KEY_ID.PLAY_PAUSE,
    CidTable.STANDARD_KEY_A:            KEY_ID.KEYBOARD_A,
    CidTable.STANDARD_KEY_B:            KEY_ID.KEYBOARD_B,
    CidTable.STANDARD_KEY_C:            KEY_ID.KEYBOARD_C,
    CidTable.STANDARD_KEY_D:            KEY_ID.KEYBOARD_D,
    CidTable.STANDARD_KEY_E:            KEY_ID.KEYBOARD_E,
    CidTable.STANDARD_KEY_F:            KEY_ID.KEYBOARD_F,
    CidTable.STANDARD_KEY_G:            KEY_ID.KEYBOARD_G,
    CidTable.STANDARD_KEY_H:            KEY_ID.KEYBOARD_H,
    CidTable.STANDARD_KEY_I:            KEY_ID.KEYBOARD_I,
    CidTable.STANDARD_KEY_J:            KEY_ID.KEYBOARD_J,
    CidTable.STANDARD_KEY_K:            KEY_ID.KEYBOARD_K,
    CidTable.STANDARD_KEY_L:            KEY_ID.KEYBOARD_L,
    CidTable.STANDARD_KEY_M:            KEY_ID.KEYBOARD_M,
    CidTable.STANDARD_KEY_N:            KEY_ID.KEYBOARD_N,
    CidTable.STANDARD_KEY_O:            KEY_ID.KEYBOARD_O,
    CidTable.STANDARD_KEY_P:            KEY_ID.KEYBOARD_P,
    CidTable.STANDARD_KEY_Q:            KEY_ID.KEYBOARD_Q,
    CidTable.STANDARD_KEY_R:            KEY_ID.KEYBOARD_R,
    CidTable.STANDARD_KEY_S:            KEY_ID.KEYBOARD_S,
    CidTable.STANDARD_KEY_T:            KEY_ID.KEYBOARD_T,
    CidTable.STANDARD_KEY_U:            KEY_ID.KEYBOARD_U,
    CidTable.STANDARD_KEY_V:            KEY_ID.KEYBOARD_V,
    CidTable.STANDARD_KEY_W:            KEY_ID.KEYBOARD_W,
    CidTable.STANDARD_KEY_X:            KEY_ID.KEYBOARD_X,
    CidTable.STANDARD_KEY_Y:            KEY_ID.KEYBOARD_Y,
    CidTable.STANDARD_KEY_Z:            KEY_ID.KEYBOARD_Z,
    CidTable.BLUETOOTH:                 KEY_ID.BLE_CONNECTION,
    CidTable.LS2_BTN:                   KEY_ID.LS2_CONNECTION,
    CidTable.STANDARD_0:                KEY_ID.KEYBOARD_0,
    CidTable.STANDARD_1:                KEY_ID.KEYBOARD_1,
    CidTable.STANDARD_2:                KEY_ID.KEYBOARD_2,
    CidTable.STANDARD_3:                KEY_ID.KEYBOARD_3,
    CidTable.STANDARD_4:                KEY_ID.KEYBOARD_4,
    CidTable.STANDARD_5:                KEY_ID.KEYBOARD_5,
    CidTable.STANDARD_6:                KEY_ID.KEYBOARD_6,
    CidTable.STANDARD_7:                KEY_ID.KEYBOARD_7,
    CidTable.STANDARD_8:                KEY_ID.KEYBOARD_8,
    CidTable.STANDARD_9:                KEY_ID.KEYBOARD_9,
    CidTable.STANDARD_PERIOD_AND_MORE:  KEY_ID.KEYBOARD_PERIOD_AND_MORE,
    CidTable.STANDARD_COMMA_AND_LESS:   KEY_ID.KEYBOARD_COMMA_AND_LESS,
    CidTable.INTERNATIONAL1:            KEY_ID.KEYBOARD_INTERNATIONAL1,
    CidTable.RO:                        KEY_ID.RO,
    CidTable.INTERNATIONAL2:            KEY_ID.KEYBOARD_INTERNATIONAL2,
    CidTable.KATAHIRA:                  KEY_ID.KATAHIRA,
    CidTable.INTERNATIONAL3:            KEY_ID.KEYBOARD_INTERNATIONAL3,
    CidTable.YEN:                       KEY_ID.YEN,
    CidTable.INTERNATIONAL4:            KEY_ID.KEYBOARD_INTERNATIONAL4,
    CidTable.HENKAN:                    KEY_ID.HENKAN,
    CidTable.INTERNATIONAL5:            KEY_ID.KEYBOARD_INTERNATIONAL5,
    CidTable.MUHENKAN:                  KEY_ID.MUHENKAN,
    CidTable.STANDARD_ENTER:            KEY_ID.KEYBOARD_RETURN_ENTER,
    CidTable.F1:                        KEY_ID.KEYBOARD_F1,
    CidTable.F2:                        KEY_ID.KEYBOARD_F2,
    CidTable.F3:                        KEY_ID.KEYBOARD_F3,
    CidTable.F4:                        KEY_ID.KEYBOARD_F4,
    CidTable.F5:                        KEY_ID.KEYBOARD_F5,
    CidTable.F6:                        KEY_ID.KEYBOARD_F6,
    CidTable.F7:                        KEY_ID.KEYBOARD_F7,
    CidTable.F8:                        KEY_ID.KEYBOARD_F8,
    CidTable.F9:                        KEY_ID.KEYBOARD_F9,
    CidTable.F10:                       KEY_ID.KEYBOARD_F10,
    CidTable.F11:                       KEY_ID.KEYBOARD_F11,
    CidTable.F12:                       KEY_ID.KEYBOARD_F12,
    CidTable.PRINT_SCREEN:              KEY_ID.KEYBOARD_PRINT_SCREEN,
    CidTable.PAUSE_BREAK:               KEY_ID.KEYBOARD_PAUSE,
    CidTable.SCROLL_LOCK:               KEY_ID.KEYBOARD_SCROLL_LOCK,
    CidTable.CONTEXTUAL_MENU:           KEY_ID.CONTEXTUAL_MENU,
    CidTable.STANDARD_BACKSPACE:        KEY_ID.KEYBOARD_BACKSPACE,
    CidTable.STANDARD_ESC:              KEY_ID.KEYBOARD_ESCAPE,
    CidTable.STANDARD_SPACE_BAR:        KEY_ID.KEYBOARD_SPACE_BAR,
    CidTable.STANDARD_FORWARD_SLASH_AND_QUESTION_MARK: KEY_ID.KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK,
    CidTable.STANDARD_DASH_AND_UNDERSCORE: KEY_ID.KEYBOARD_DASH_AND_UNDERSCORE,
    CidTable.STANDARD_EQUAL_AND_PLUS:   KEY_ID.KEYBOARD_EQUAL_AND_PLUS,
    CidTable.STANDARD_LEFT_BRACKET_AND_BRACE: KEY_ID.KEYBOARD_LEFT_BRACKET_AND_BRACE,
    CidTable.STANDARD_RIGHT_BRACKET_AND_BRACE: KEY_ID.KEYBOARD_RIGHT_BRACKET_AND_BRACE,
    CidTable.STANDARD_SEMICOLON_AND_COLON: KEY_ID.KEYBOARD_SEMICOLON_AND_COLON,
    CidTable.STANDARD_APOSTROPHE_AND_QUOTATION_MARK: KEY_ID.KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK,
    CidTable.NON_US_AND_TILDE: KEY_ID.KEYBOARD_NON_US_AND_TILDE,
    CidTable.NON_US_BACKSLASH_AND_PIPE: KEY_ID.KEYBOARD_NON_US_BACKSLASH_AND_PIPE,
    CidTable.NUMPAD_NUM_LOCK_AND_CLEAR: KEY_ID.KEYPAD_NUM_LOCK_AND_CLEAR,
    CidTable.NUMPAD_SLASH:              KEY_ID.KEYPAD_FORWARD_SLASH,
    CidTable.NUMPAD_ASTERISK:           KEY_ID.KEYPAD_ASTERISK,
    CidTable.NUMPAD_MINUS:              KEY_ID.KEYPAD_MINUS,
    CidTable.NUMPAD_PLUS:               KEY_ID.KEYPAD_PLUS,
    CidTable.NUMPAD_ENTER:              KEY_ID.KEYPAD_ENTER,
    CidTable.NUMPAD_1_AND_END:          KEY_ID.KEYPAD_1_AND_END,
    CidTable.NUMPAD_2_AND_DOWN_ARROW:   KEY_ID.KEYPAD_2_AND_DOWN_ARROW,
    CidTable.NUMPAD_3_AND_PAGE_DOWN:    KEY_ID.KEYPAD_3_AND_PAGE_DN,
    CidTable.NUMPAD_4_AND_LEFT_ARROW:   KEY_ID.KEYPAD_4_AND_LEFT_ARROW,
    CidTable.NUMPAD_5:                  KEY_ID.KEYPAD_5,
    CidTable.NUMPAD_6_AND_RIGHT_ARROW:  KEY_ID.KEYPAD_6_AND_RIGHT_ARROW,
    CidTable.NUMPAD_7_AND_HOME:         KEY_ID.KEYPAD_7_AND_HOME,
    CidTable.NUMPAD_8_AND_UP_ARROW:     KEY_ID.KEYPAD_8_AND_UP_ARROW,
    CidTable.NUMPAD_9_AND_PAGE_UP:      KEY_ID.KEYPAD_9_AND_PAGE_UP,
    CidTable.NUMPAD_0_AND_INSERT:       KEY_ID.KEYPAD_0_AND_INSERT,
    CidTable.NUMPAD_FULL_STOP_AND_DELETE: KEY_ID.KEYPAD_PERIOD_AND_DELETE,
    CidTable.LS2_BLE_CONNECTION_TOGGLE: KEY_ID.LS2_BLE_CONNECTION_TOGGLE,
    CidTable.KEY_BRIGHTNESS_CYCLE:      KEY_ID.DIMMING_KEY,
    CidTable.GAME_MODE_BTN:             KEY_ID.GAME_MODE_KEY,
    CidTable.LEFT_ALT:     KEY_ID.KEYBOARD_LEFT_ALT,
    CidTable.LEFT_GUI:     KEY_ID.KEYBOARD_LEFT_WIN_OR_OPTION,
    CidTable.RIGHT_ALT:    KEY_ID.KEYBOARD_RIGHT_ALT,
    CidTable.RIGHT_GUI:    KEY_ID.KEYBOARD_RIGHT_WIN_OR_OPTION,
    CidTable.G_KEY1:       KEY_ID.G_1,
    CidTable.G_KEY2:       KEY_ID.G_2,
    CidTable.G_KEY3:       KEY_ID.G_3,
    CidTable.G_KEY4:       KEY_ID.G_4,
    CidTable.G_KEY5:       KEY_ID.G_5,
    CidTable.G_KEY6:       KEY_ID.G_6,
    CidTable.G_KEY7:       KEY_ID.G_7,
    CidTable.G_KEY8:       KEY_ID.G_8,
    CidTable.G_KEY9:       KEY_ID.G_9,

    CidTable.ROLLER0_SCROLL_UP:         KEY_ID.ROLLER0_SCROLL_UP,
    CidTable.ROLLER0_SCROLL_DOWN:       KEY_ID.ROLLER0_SCROLL_DOWN,
    CidTable.ROLLER1_SCROLL_UP:         KEY_ID.ROLLER1_SCROLL_UP,
    CidTable.ROLLER1_SCROLL_DOWN:       KEY_ID.ROLLER1_SCROLL_DOWN,

    CidTable.LAUNCH_DIDOT:              KEY_ID.LAUNCH_DIDOT,

    CidTable.SMART_ACTION_1:            KEY_ID.SMART_ACTION_1,
    CidTable.SMART_ACTION_2:            KEY_ID.SMART_ACTION_2,
    CidTable.SMART_ACTION_3:            KEY_ID.SMART_ACTION_3,
    CidTable.SMART_ACTION_4:            KEY_ID.SMART_ACTION_4,
    CidTable.BACKLIGHT_CYCLING:         KEY_ID.BACKLIGHT_CYCLING,

    CidTable.LEFT_PROFILE_ARROW:        KEY_ID.BUTTON_10,
    CidTable.RIGHT_PROFILE_ARROW:        KEY_ID.BUTTON_11,
}


CONSUMER_CID_LIST = [
    CidTable.BRIGHTNESS_DOWN, CidTable.BRIGHTNESS_UP, CidTable.PREV_TRACK, CidTable.PLAY_PAUSE, CidTable.NEXT_TRACK,
    CidTable.MUTE, CidTable.VOLUME_DOWN, CidTable.VOLUME_UP, CidTable.CALCULATOR, CidTable.MULTI_PLATFORM_SEARCH,
    CidTable.HOME, CidTable.BACK, CidTable.PLAY_PAUSE_DOUBLE_TRACK, CidTable.STOP,
]

# ------------------------------------------------------------------------------
# END OF FILE
# ------------------------------------------------------------------------------
