#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------------
# Python Test Box
# ----------------------------------------------------------------------------
"""
:package: pyhid.hid.usbhidusagetable
:brief: USB HID usage table. http://www.freebsddiary.org/APC/usb_hid_usages
:author: Christophe Roquebert <croquebert@logitech.com>
:date: 2020/07/22
"""
# ----------------------------------------------------------------------------
# imports
# ----------------------------------------------------------------------------
from pylibrary.emulator.keyid import KEY_ID
from pylibrary.tools.hexlist import HexList
from pylibrary.tools.numeral import to_endian_list


# ------------------------------------------------------------------------------
# Implementation
# ------------------------------------------------------------------------------
class KEYBOARD_HID_USAGE:
    """
    page 7	Keyboard
    """
    RESERVED_NO_EVENT_INDICATED = 0x00
    KEYBOARD_ERROR_ROLLOVER = 0x01
    KEYBOARD_POST_FAIL = 0x02
    KEYBOARD_ERROR_UNDEFINED = 0x03
    KEYBOARD_A_AND_A = 0x04
    KEYBOARD_B_AND_B = 0x05
    KEYBOARD_C_AND_C = 0x06
    KEYBOARD_D_AND_D = 0x07
    KEYBOARD_E_AND_E = 0x08
    KEYBOARD_F_AND_F = 0x09
    KEYBOARD_G_AND_G = 0x0A
    KEYBOARD_H_AND_H = 0x0B
    KEYBOARD_I_AND_I = 0x0C
    KEYBOARD_J_AND_J = 0x0D
    KEYBOARD_K_AND_K = 0x0E
    KEYBOARD_L_AND_L = 0x0F
    KEYBOARD_M_AND_M = 0x10
    KEYBOARD_N_AND_N = 0x11
    KEYBOARD_O_AND_O = 0x12
    KEYBOARD_P_AND_P = 0x13
    KEYBOARD_Q_AND_Q = 0x14
    KEYBOARD_R_AND_R = 0x15
    KEYBOARD_S_AND_S = 0x16
    KEYBOARD_T_AND_T = 0x17
    KEYBOARD_U_AND_U = 0x18
    KEYBOARD_V_AND_V = 0x19
    KEYBOARD_W_AND_W = 0x1A
    KEYBOARD_X_AND_X = 0x1B
    KEYBOARD_Y_AND_Y = 0x1C
    KEYBOARD_Z_AND_Z = 0x1D
    KEYBOARD_1_AND_ = 0x1E
    KEYBOARD_2_AND_ = 0x1F
    KEYBOARD_3_AND_ = 0x20
    KEYBOARD_4_AND_ = 0x21
    KEYBOARD_5_AND_ = 0x22
    KEYBOARD_6_AND_ = 0x23
    KEYBOARD_7_AND_ = 0x24
    KEYBOARD_8_AND_ = 0x25
    KEYBOARD_9_AND_ = 0x26
    KEYBOARD_0_AND_ = 0x27
    KEYBOARD_RETURN_ENTER = 0x28
    KEYBOARD_ESCAPE = 0x29
    KEYBOARD_DELETE_BACKSPACE = 0x2A
    KEYBOARD_TAB = 0x2B
    KEYBOARD_SPACE_BAR = 0x2C
    KEYBOARD_DASH_AND_UNDERSCORE = 0x2D
    KEYBOARD_EQUAL_AND_PLUS = 0x2E
    KEYBOARD_LEFT_BRACKET_AND_BRACE = 0x2F
    KEYBOARD_RIGHT_BRACKET_AND_BRACE = 0x30
    KEYBOARD_BACKSLASH_AND_PIPE = 0x31
    KEYBOARD_NON_US_AND_TILDE = 0x32
    KEYBOARD_SEMICOLON_AND_COLON = 0x33
    KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK = 0x34
    KEYBOARD_GRAVE_ACCENT_AND_TILDE = 0x35
    KEYBOARD_COMMA_AND_LESS = 0x36
    KEYBOARD_PERIOD_AND_MORE = 0x37
    KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK = 0x38
    KEYBOARD_CAPS_LOCK = 0x39
    KEYBOARD_F1 = 0x3A
    KEYBOARD_F2 = 0x3B
    KEYBOARD_F3 = 0x3C
    KEYBOARD_F4 = 0x3D
    KEYBOARD_F5 = 0x3E
    KEYBOARD_F6 = 0x3F
    KEYBOARD_F7 = 0x40
    KEYBOARD_F8 = 0x41
    KEYBOARD_F9 = 0x42
    KEYBOARD_F10 = 0x43
    KEYBOARD_F11 = 0x44
    KEYBOARD_F12 = 0x45
    KEYBOARD_PRINT_SCREEN = 0x46
    KEYBOARD_SCROLL_LOCK = 0x47
    KEYBOARD_PAUSE = 0x48
    KEYBOARD_INSERT = 0x49
    KEYBOARD_HOME = 0x4A
    KEYBOARD_PAGE_UP = 0x4B
    KEYBOARD_DELETE_FORWARD = 0x4C
    KEYBOARD_END = 0x4D
    KEYBOARD_PAGE_DOWN = 0x4E
    KEYBOARD_RIGHT_ARROW = 0x4F
    KEYBOARD_LEFT_ARROW = 0x50
    KEYBOARD_DOWN_ARROW = 0x51
    KEYBOARD_UP_ARROW = 0x52
    KEYPAD_NUM_LOCK_AND_CLEAR = 0x53
    KEYPAD_FORWARD_SLASH = 0x54
    KEYPAD_ASTERISK = 0x55
    KEYPAD_DASH = 0x56
    KEYPAD_PLUS = 0x57
    KEYPAD_ENTER = 0x58
    KEYPAD_1_AND_END = 0x59
    KEYPAD_2_AND_DOWN_ARROW = 0x5A
    KEYPAD_3_AND_PAGE_DN = 0x5B
    KEYPAD_4_AND_LEFT_ARROW = 0x5C
    KEYPAD_5 = 0x5D
    KEYPAD_6_AND_RIGHT_ARROW = 0x5E
    KEYPAD_7_AND_HOME = 0x5F
    KEYPAD_8_AND_UP_ARROW = 0x60
    KEYPAD_9_AND_PAGE_UP = 0x61
    KEYPAD_0_AND_INSERT = 0x62
    KEYPAD_COMMA_AND_DELETE = 0x63
    KEYBOARD_NON_US_BACKSLASH_AND_PIPE = 0x64
    KEYBOARD_APPLICATION = 0x65
    KEYBOARD_POWER = 0x66
    KEYPAD_EQUAL = 0x67
    KEYBOARD_F13 = 0x68
    KEYBOARD_F14 = 0x69
    KEYBOARD_F15 = 0x6A
    KEYBOARD_F16 = 0x6B
    KEYBOARD_F17 = 0x6C
    KEYBOARD_F18 = 0x6D
    KEYBOARD_F19 = 0x6E
    KEYBOARD_F20 = 0x6F
    KEYBOARD_F21 = 0x70
    KEYBOARD_F22 = 0x71
    KEYBOARD_F23 = 0x72
    KEYBOARD_F24 = 0x73
    KEYBOARD_EXECUTE = 0x74
    KEYBOARD_HELP = 0x75
    KEYBOARD_MENU = 0x76
    KEYBOARD_SELECT = 0x77
    KEYBOARD_STOP = 0x78
    KEYBOARD_AGAIN = 0x79
    KEYBOARD_UNDO = 0x7A
    KEYBOARD_CUT = 0x7B
    KEYBOARD_COPY = 0x7C
    KEYBOARD_PASTE = 0x7D
    KEYBOARD_FIND = 0x7E
    KEYBOARD_MUTE = 0x7F
    KEYBOARD_VOLUME_UP = 0x80
    KEYBOARD_VOLUME_DOWN = 0x81
    KEYBOARD_LOCKING_CAPS_LOCK = 0x82
    KEYBOARD_LOCKING_NUM_LOCK = 0x83
    KEYBOARD_LOCKING_SCROLL_LOCK = 0x84
    KEYPAD_COMMA = 0x85
    KEYPAD_EQUAL_SIGN = 0x86
    KEYBOARD_INTERNATIONAL1 = 0x87
    KEYBOARD_INTERNATIONAL2 = 0x88
    KEYBOARD_INTERNATIONAL3 = 0x89
    KEYBOARD_INTERNATIONAL4 = 0x8A
    KEYBOARD_INTERNATIONAL5 = 0x8B
    KEYBOARD_INTERNATIONAL6 = 0x8C
    KEYBOARD_INTERNATIONAL7 = 0x8D
    KEYBOARD_INTERNATIONAL8 = 0x8E
    KEYBOARD_INTERNATIONAL9 = 0x8F
    KEYBOARD_LANG1 = 0x90
    KEYBOARD_LANG2 = 0x91
    KEYBOARD_LANG3 = 0x92
    KEYBOARD_LANG4 = 0x93
    KEYBOARD_LANG5 = 0x94
    KEYBOARD_LANG6 = 0x95
    KEYBOARD_LANG7 = 0x96
    KEYBOARD_LANG8 = 0x97
    KEYBOARD_LANG9 = 0x98
    KEYBOARD_ALTERNATE_ERASE = 0x99
    KEYBOARD_SYS_REQ_ATTENTION = 0x9A
    KEYBOARD_CANCEL = 0x9B
    KEYBOARD_CLEAR = 0x9C
    KEYBOARD_PRIOR = 0x9D
    KEYBOARD_RETURN = 0x9E
    KEYBOARD_SEPARATOR = 0x9F
    KEYBOARD_OUT = 0xA0
    KEYBOARD_OPER = 0xA1
    KEYBOARD_CLEAR_AGAIN = 0xA2
    KEYBOARD_CRSEL_PROPS = 0xA3
    KEYBOARD_EXSEL = 0xA4
    KEYPAD_00 = 0xB0
    KEYPAD_000 = 0xB1
    THOUSANDS_SEPARATOR = 0xB2
    DECIMAL_SEPARATOR = 0xB3
    CURRENCY_UNIT = 0xB4
    CURRENCY_SUB_UNIT = 0xB5
    KEYPAD_RIGHT_PARENTHESES = 0xB6
    KEYPAD_LEFT_PARENTHESES = 0xB7
    KEYPAD_RIGHT_BRACE = 0xB8
    KEYPAD_LEFT_BRACE = 0xB9
    KEYPAD_TAB = 0xBA
    KEYPAD_BACKSPACE = 0xBB
    KEYPAD_A = 0xBC
    KEYPAD_B = 0xBD
    KEYPAD_C = 0xBE
    KEYPAD_D = 0xBF
    KEYPAD_E = 0xC0
    KEYPAD_F = 0xC1
    KEYPAD_XOR = 0xC2
    KEYPAD_CARET = 0xC3
    KEYPAD_PERCENT = 0xC4
    KEYPAD_LESS = 0xC5
    KEYPAD_MORE = 0xC6
    KEYPAD_AMPERSAND = 0xC7
    KEYPAD_LOGICAL_AND = 0xC8
    KEYPAD_VERTICAL_BAR = 0xC9
    KEYPAD_LOGICAL_OR = 0xCA
    KEYPAD_COLON = 0xCB
    KEYPAD_HASH = 0xCC
    KEYPAD_SPACE = 0xCD
    KEYPAD_AT_SIGN = 0xCE
    KEYPAD_EXCLAMATION_MARK = 0xCF
    KEYPAD_MEMORY_STORE = 0xD0
    KEYPAD_MEMORY_RECALL = 0xD1
    KEYPAD_MEMORY_CLEAR = 0xD2
    KEYPAD_MEMORY_ADD = 0xD3
    KEYPAD_MEMORY_SUBSTRACT = 0xD4
    KEYPAD_MEMORY_MULTIPLY = 0xD5
    KEYPAD_MEMORY_DIVIDE = 0xD6
    KEYPAD_PLUS_MINUS = 0xD7
    KEYPAD_CLEAR = 0xD8
    KEYPAD_CLEAR_ENTRY = 0xD9
    KEYPAD_BINARY = 0xDA
    KEYPAD_OCTAL = 0xDB
    KEYPAD_DECIMAL = 0xDC
    KEYPAD_HEXADECIMAL = 0xDD
    KEYBOARD_LEFT_CONTROL = 0xE0
    KEYBOARD_LEFTSHIFT = 0xE1
    KEYBOARD_LEFT_ALT = 0xE2
    KEYBOARD_LEFT_GUI = 0xE3
    KEYBOARD_RIGHT_CONTROL = 0xE4
    KEYBOARD_RIGHTSHIFT = 0xE5
    KEYBOARD_RIGHT_ALT = 0xE6
    KEYBOARD_RIGHT_GUI = 0xE7
# end class KEYBOARD_HID_USAGE


class MouseHidUsage:
    """
    page 9	Button
    0x00	No Button Pressed
    *	    Button %d
    """
    LEFT_BUTTON = 0x01
    RIGHT_BUTTON = 0x02
    MIDDLE_BUTTON = 0x03
    BACK_BUTTON = 0x04
    FORWARD_BUTTON = 0x05
# end class MouseHidUsage


class ConsumerHidUsage:
    """
    Page 12 - Consumer
    """
    CONSUMER_CONTROL = 0x01
    NUMERIC_KEY_PAD = 0x02
    PROGRAMMABLE_BUTTONS = 0x03
    MICROPHONE = 0x04
    HEADPHONE = 0x05
    GRAPHIC_EQUALIZER = 0x06
    PLUS10 = 0x20
    PLUS100 = 0x21
    AM_PM = 0x22
    POWER = 0x30
    RESET = 0x31
    SLEEP = 0x32
    SLEEP_AFTER = 0x33
    SLEEP_MODE = 0x34
    ILLUMINATION = 0x35
    FUNCTION_BUTTONS = 0x36
    MENU = 0x40
    MENU__PICK = 0x41
    MENU_UP = 0x42C
    MENU_DOWN = 0x43
    MENU_LEFT = 0x44
    MENU_RIGHT = 0x45
    MENU_ESCAPE = 0x46
    MENU_VALUE_INCREASE = 0x47
    MENU_VALUE_DECREASE = 0x48
    DATA_ON_SCREEN = 0x60
    CLOSED_CAPTION = 0x61
    CLOSED_CAPTION_SELECT = 0x62
    VCR_TV = 0x63
    BROADCAST_MODE = 0x64
    SNAPSHOT = 0x65
    STILL = 0x66
    BRIGHTNESS_UP = 0x6F
    BRIGHTNESS_DOWN = 0x70
    KBD_BACKLIGHT_UP = 0x79
    KBD_BACKLIGHT_DOWN = 0x7A
    SELECTION = 0x80
    ASSIGN_SELECTION = 0x81
    MODE_STEP = 0x82
    RECALL_LAST = 0x83
    ENTER_CHANNEL = 0x84
    ORDER_MOVIE = 0x85
    CHANNEL = 0x86
    MEDIA_SELECTION = 0x87
    MEDIA_SELECT_COMPUTER = 0x88
    MEDIA_SELECT_TV = 0x89
    MEDIA_SELECT_WWW = 0x8A
    MEDIA_SELECT_DVD = 0x8B
    MEDIA_SELECT_TELEPHONE = 0x8C
    MEDIA_SELECT_PROGRAM_GUIDE = 0x8D
    MEDIA_SELECT_VIDEO_PHONE = 0x8E
    MEDIA_SELECT_GAMES = 0x8F
    MEDIA_SELECT_MESSAGES = 0x90
    MEDIA_SELECT_CD = 0x91
    MEDIA_SELECT_VCR = 0x92
    MEDIA_SELECT_TUNER = 0x93
    QUIT = 0x94
    HELP = 0x95
    MEDIA_SELECT_TAPE = 0x96
    MEDIA_SELECT_CABLE = 0x97
    MEDIA_SELECT_SATELLITE = 0x98
    MEDIA_SELECT_SECURITY = 0x99
    MEDIA_SELECT_HOME = 0x9A
    MEDIA_SELECT_CALL = 0x9B
    CHANNEL_INCREMENT = 0x9C
    CHANNEL_DECREMENT = 0x9D
    MEDIA_SELECT_SAP = 0x9E
    VCR_PLUS = 0xA0
    ONCE = 0xA1
    DAILY = 0xA2
    WEEKLY = 0xA3
    MONTHLY = 0xA4
    PLAY = 0xB0
    PAUSE = 0xB1
    RECORD = 0xB2
    FAST_FORWARD = 0xB3
    REWIND = 0xB4
    SCAN_NEXT_TRACK = 0xB5
    SCAN_PREVIOUS_TRACK = 0xB6
    STOP = 0xB7
    EJECT = 0xB8
    RANDOM_PLAY = 0xB9
    SELECT_DISC = 0xBA
    ENTER_DISC = 0xBB
    REPEAT = 0xBC
    TRACKING = 0xBD
    TRACK_NORMAL = 0xBE
    SLOW_TRACKING = 0xBF
    FRAME_FORWARD = 0xC0
    FRAME_BACK = 0xC1
    MARK = 0xC2
    CLEAR_MARK = 0xC3
    REPEAT_FROM_MARK = 0xC4
    RETURN_TO_MARK = 0xC5
    SEARCH_MARK_FORWARD = 0xC6
    SEARCH_MARK_BACKWARDS = 0xC7
    COUNTER_RESET = 0xC8
    SHOW_COUNTER = 0xC9
    TRACKING_INCREMENT = 0xCA
    TRACKING_DECREMENT = 0xCB
    STOP_EJECT = 0xCC
    PLAY_PAUSE = 0xCD
    PLAY_SKIP = 0xCE
    START_OR_STOP_MICROPHONE_CAPTURE = 0xD5
    VOICE_DICTATION = 0xD8
    EMOJI_PICKER = 0xD9
    VOLUME = 0xE0
    BALANCE = 0xE1
    MUTE = 0xE2
    BASS = 0xE3
    TREBLE = 0xE4
    BASS_BOOST = 0xE5
    SURROUND_MODE = 0xE6
    LOUDNESS = 0xE7
    MPX = 0xE8
    VOLUME_UP = 0xE9
    VOLUME_DOWN = 0xEA
    SPEED_SELECT = 0xF0
    PLAYBACK_SPEED = 0xF1
    STANDARD_PLAY = 0xF2
    LONG_PLAY = 0xF3
    EXTENDED_PLAY = 0xF4
    SLOW = 0xF5
    FAN_ENABLE = 0x100
    FAN_SPEED = 0x101
    LIGHT = 0x102
    LIGHT_ILLUMINATION_LEVEL = 0x103
    CLIMATE_TROL_ENABLE = 0x104
    ROOM_TEMPERATURE = 0x105
    SECURITY_ENABLE = 0x106
    FIRE_ALARM = 0x107
    POLICE_ALARM = 0x108
    PROXIMITY = 0x109
    MOTION = 0x10A
    DURESS_ALARM = 0x10B
    HOLDUP_ALARM = 0x10C
    MEDICAL_ALARM = 0x10D
    BALANCE_RIGHT = 0x150
    BALANCE_LEFT = 0x151
    BASS_INCREMENT = 0x152
    BASS_DECREMENT = 0x153
    TREBLE_INCREMENT = 0x154
    TREBLE_DECREMENT = 0x155
    SPEAKER_SYSTEM = 0x160
    CHANNEL_LEFT = 0x161
    CHANNEL_RIGHT = 0x162
    CHANNEL_CENTER = 0x163
    CHANNEL_FRONT = 0x164
    CHANNEL_CENTER_FRONT = 0x165
    CHANNEL_SIDE = 0x166
    CHANNEL_SURROUND = 0x167
    CHANNEL_LOW_FREQUENCY_ENHANCEMENT = 0x168
    CHANNEL_TOP = 0x169
    CHANNEL_UNKNOWN = 0x16A
    SUB_CHANNEL = 0x170
    SUB_CHANNEL_INCREMENT = 0x171
    SUB_CHANNEL_DECREMENT = 0x172
    ALTERNATE_AUDIO_INCREMENT = 0x173
    ALTERNATE_AUDIO_DECREMENT = 0x174
    APPLICATION_LAUNCH_BUTTONS = 0x180
    AL_LAUNCH_BUTTON_FIGURATION_TOOL = 0x181
    AL_PROGRAMMABLE_BUTTON_FIGURATION = 0x182
    AL_SUMER_TROL_FIGURATION = 0x183
    AL_WORD_PROCESSOR = 0x184
    AL_TEXT_EDITOR = 0x185
    AL_SPREADSHEET = 0x186
    AL_GRAPHICS_EDITOR = 0x187
    AL_PRESENTATION_APP = 0x188
    AL_DATABASE_APP = 0x189
    AL_EMAIL_READER = 0x18A
    AL_NEWSREADER = 0x18B
    AL_VOICEMAIL = 0x18C
    AL_TACTS_ADDRESS_BOOK = 0x18D
    AL_CALENDAR_SCHEDULE = 0x18E
    AL_TASK_PROJECT_MANAGER = 0x18F
    AL_LOG_JOURNAL_TIMECARD = 0x190
    AL_CHECKBOOK_FINANCE = 0x191
    AL_CALCULATOR = 0x192
    AL_A_V_CAPTURE_PLAYBACK = 0x193
    AL_LOCAL_MACHINE_BROWSER = 0x194
    AL_LAN_WAN_BROWSER = 0x195
    AL_INTERNET_BROWSER = 0x196
    AL_REMOTE_NETWORKING_ISP_NECT = 0x197
    AL_NETWORK_FERENCE = 0x198
    AL_NETWORK_CHAT = 0x199
    AL_TELEPHONY_DIALER = 0x19A
    AL_LOGON = 0x19B
    AL_LOGOFF = 0x19C
    AL_LOGON_LOGOFF = 0x19D
    AL_TERMINAL_LOCK_SCREENSAVER = 0x19E
    AL_CONTROL_PANEL = 0x19F
    AL_COMMAND_LINE_PROCESSOR_RUN = 0x1A0
    AL_PROCESS_TASK_MANAGER = 0x1A1
    AL_SELECT_TAST_APPLICATION = 0x1A2
    AL_NEXT_TASK_APPLICATION = 0x1A3
    AL_PREVIOUS_TASK_APPLICATION = 0x1A4
    AL_PREEMPTIVE_HALT_TASK_APPLICATION = 0x1A5
    AL_INTEGRATED_HELP_CENTER = 0x1A6
    AL_DOCUMENTS = 0x1A7
    AL_THESAURUS = 0x1A8
    AL_DICTIONARY = 0x1A9
    AL_DESKTOP = 0x1AA
    AL_SPELL_CHECK = 0x1AB
    AL_GRAMMAR_CHECK = 0x1AC
    AL_WIRELESS_STATUS = 0x1AD
    AL_KEYBOARD_LAYOUT = 0x1AE
    AL_VIRUS_PROTECTION = 0x1AF
    AL_ENCRYPTION = 0x1B0
    AL_SCREEN_SAVER = 0x1B1
    AL_ALARMS = 0x1B2
    AL_CLOCK = 0x1B3
    AL_FILE_BROWSER = 0x1B4
    AL_POWER_STATUS = 0x1B5
    AL_IMAGE_BROWSER = 0x1B6
    AL_AUDIO_BROWSER = 0x1B7
    AL_MOVIE_BROWSER = 0x1B8
    AL_DIGITAL_RIGHTS_MANAGER = 0x1B9
    AL_DIGITAL_WALLET = 0x1BA
    AL_INSTANT_MESSAGING = 0x1BC
    AL_OEM_FEATURES_TIPS_TUTORIAL_BROWSER = 0x1BD
    AL_OEM_HELP = 0x1BE
    AL_ONLINE_COMMUNITY = 0x1BF
    AL_ENTERTAINMENT_TENT_BROWSER = 0x1C0
    AL_ONLINE_SHOPPING_BROWSER = 0x1C1
    AL_SMART_CARD_INFORMATION_HELP = 0x1C2
    AL_MARKET_MONITOR_FINANCE_BROWSER = 0x1C3
    AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER = 0x1C4
    AL_ONLINE_ACTIVITY_BROWSER = 0x1C5
    AL_RESEARCH_SEARCH_BROWSER = 0x1C6
    AL_AUDIO_PLAYER = 0x1C7
    GENERIC_GUI_APPLICATION_TROLS = 0x200
    AC_NEW = 0x201
    AC_OPEN = 0x202
    AC_CLOSE = 0x203
    AC_EXIT = 0x204
    AC_MAXIMIZE = 0x205
    AC_MINIMIZE = 0x206
    AC_SAVE = 0x207
    AC_PRINT = 0x208
    AC_PROPERTIES = 0x209
    AC_UNDO = 0x21A
    AC_COPY = 0x21B
    AC_CUT = 0x21C
    AC_PASTE = 0x21D
    AC_SELECT_ALL = 0x21E
    AC_FIND = 0x21F
    AC_FIND_AND_REPLACE = 0x220
    AC_SEARCH = 0x221
    AC_GO_TO = 0x222
    AC_HOME = 0x223
    AC_BACK = 0x224
    AC_FORWARD = 0x225
    AC_STOP = 0x226
    AC_REFRESH = 0x227
    AC_PREVIOUS_LINK = 0x228
    AC_NEXT_LINK = 0x229
    AC_BOOKMARKS = 0x22A
    AC_HISTORY = 0x22B
    AC_SUBSCRIPTIONS = 0x22C
    AC_ZOOM_IN = 0x22D
    AC_ZOOM_OUT = 0x22E
    AC_ZOOM = 0x22F
    AC_FULL_SCREEN_VIEW = 0x230
    AC_NORMAL_VIEW = 0x231
    AC_VIEW_TOGGLE = 0x232
    AC_SCROLL_UP = 0x233
    AC_SCROLL_DOWN = 0x234
    AC_SCROLL = 0x235
    AC_PAN_LEFT = 0x236
    AC_PAN_RIGHT = 0x237
    AC_PAN = 0x0238
    AC_NEW_WINDOW = 0x0239
    AC_TILE_HORIZONTALLY = 0x23A
    AC_TILE_VERTICALLY = 0x23B
    AC_FORMAT = 0x23C
    AC_EDIT = 0x23D
    AC_BOLD = 0x23E
    AC_ITALICS = 0x23F
    AC_UNDERLINE = 0x240
    AC_STRIKE_THROUGH = 0x241
    AC_SUBSCRIPT = 0x242
    AC_SUPERSCRIPT = 0x243
    AC_ALL_CAPS = 0x244
    AC_ROTATE = 0x245
    AC_RESIZE = 0x246
    AC_FILP_HORIZONTAL = 0x247
    AC_FLIP_VERTICAL = 0x248
    AC_MIRROR_HORIZONTAL = 0x249
    AC_MIRROR_VERTICAL = 0x24A
    AC_FONT_SELECT = 0x24B
    AC_NEXT_KEYBOARD_LAYOUT_SELECT = 0x29D
    RESERVED_29E = 0x29E
    OVERVIEW = 0x29F
    AC_LAUNCHPAD = 0x2A0
    AC_DESKTOP_SHOW_ALL_APPLICATIONS = 0x2A2
    PRIVACY_SCREEN_TOGGLE = 0x2D0
# end class ConsumerHidUsage


class GenericHidUsage:
    """
    Page 1 - Generic Desktop
    """
    SYSTEM_CONTROL = 0x80
    SYSTEM_POWER_DOWN = 0x81
    SYSTEM_SLEEP = 0x82
    SYSTEM_WAKE_UP = 0x83
    SYSTEM_DO_NOT_DISTURB = 0x9B
    SYSTEM_MICROPHONE_MUTE = 0xA9
    CALL_ACTIVE_LED = 0xE0
    CALL_MUTE_TOGGLE = 0xE1
    CALL_MUTE_LED = 0xE2
# end class GenericHidUsage


MOUSE_HID_USAGE_TO_KEY_ID_MAP = {
    MouseHidUsage.LEFT_BUTTON: KEY_ID.LEFT_BUTTON,
    MouseHidUsage.RIGHT_BUTTON: KEY_ID.RIGHT_BUTTON,
    MouseHidUsage.MIDDLE_BUTTON: KEY_ID.MIDDLE_BUTTON,
    MouseHidUsage.BACK_BUTTON: KEY_ID.BACK_BUTTON,
    MouseHidUsage.FORWARD_BUTTON: KEY_ID.FORWARD_BUTTON,
}

KEYBOARD_HID_USAGE_TO_KEY_ID_MAP = {
    KEYBOARD_HID_USAGE.KEYBOARD_A_AND_A: KEY_ID.KEYBOARD_A,
    KEYBOARD_HID_USAGE.KEYBOARD_B_AND_B: KEY_ID.KEYBOARD_B,
    KEYBOARD_HID_USAGE.KEYBOARD_C_AND_C: KEY_ID.KEYBOARD_C,
    KEYBOARD_HID_USAGE.KEYBOARD_D_AND_D: KEY_ID.KEYBOARD_D,
    KEYBOARD_HID_USAGE.KEYBOARD_E_AND_E: KEY_ID.KEYBOARD_E,
    KEYBOARD_HID_USAGE.KEYBOARD_F_AND_F: KEY_ID.KEYBOARD_F,
    KEYBOARD_HID_USAGE.KEYBOARD_G_AND_G: KEY_ID.KEYBOARD_G,
    KEYBOARD_HID_USAGE.KEYBOARD_H_AND_H: KEY_ID.KEYBOARD_H,
    KEYBOARD_HID_USAGE.KEYBOARD_I_AND_I: KEY_ID.KEYBOARD_I,
    KEYBOARD_HID_USAGE.KEYBOARD_J_AND_J: KEY_ID.KEYBOARD_J,
    KEYBOARD_HID_USAGE.KEYBOARD_K_AND_K: KEY_ID.KEYBOARD_K,
    KEYBOARD_HID_USAGE.KEYBOARD_L_AND_L: KEY_ID.KEYBOARD_L,
    KEYBOARD_HID_USAGE.KEYBOARD_M_AND_M: KEY_ID.KEYBOARD_M,
    KEYBOARD_HID_USAGE.KEYBOARD_N_AND_N: KEY_ID.KEYBOARD_N,
    KEYBOARD_HID_USAGE.KEYBOARD_O_AND_O: KEY_ID.KEYBOARD_O,
    KEYBOARD_HID_USAGE.KEYBOARD_P_AND_P: KEY_ID.KEYBOARD_P,
    KEYBOARD_HID_USAGE.KEYBOARD_Q_AND_Q: KEY_ID.KEYBOARD_Q,
    KEYBOARD_HID_USAGE.KEYBOARD_R_AND_R: KEY_ID.KEYBOARD_R,
    KEYBOARD_HID_USAGE.KEYBOARD_S_AND_S: KEY_ID.KEYBOARD_S,
    KEYBOARD_HID_USAGE.KEYBOARD_T_AND_T: KEY_ID.KEYBOARD_T,
    KEYBOARD_HID_USAGE.KEYBOARD_U_AND_U: KEY_ID.KEYBOARD_U,
    KEYBOARD_HID_USAGE.KEYBOARD_V_AND_V: KEY_ID.KEYBOARD_V,
    KEYBOARD_HID_USAGE.KEYBOARD_W_AND_W: KEY_ID.KEYBOARD_W,
    KEYBOARD_HID_USAGE.KEYBOARD_X_AND_X: KEY_ID.KEYBOARD_X,
    KEYBOARD_HID_USAGE.KEYBOARD_Y_AND_Y: KEY_ID.KEYBOARD_Y,
    KEYBOARD_HID_USAGE.KEYBOARD_Z_AND_Z: KEY_ID.KEYBOARD_Z,
    KEYBOARD_HID_USAGE.KEYBOARD_1_AND_: KEY_ID.KEYBOARD_1,
    KEYBOARD_HID_USAGE.KEYBOARD_2_AND_: KEY_ID.KEYBOARD_2,
    KEYBOARD_HID_USAGE.KEYBOARD_3_AND_: KEY_ID.KEYBOARD_3,
    KEYBOARD_HID_USAGE.KEYBOARD_4_AND_: KEY_ID.KEYBOARD_4,
    KEYBOARD_HID_USAGE.KEYBOARD_5_AND_: KEY_ID.KEYBOARD_5,
    KEYBOARD_HID_USAGE.KEYBOARD_6_AND_: KEY_ID.KEYBOARD_6,
    KEYBOARD_HID_USAGE.KEYBOARD_7_AND_: KEY_ID.KEYBOARD_7,
    KEYBOARD_HID_USAGE.KEYBOARD_8_AND_: KEY_ID.KEYBOARD_8,
    KEYBOARD_HID_USAGE.KEYBOARD_9_AND_: KEY_ID.KEYBOARD_9,
    KEYBOARD_HID_USAGE.KEYBOARD_0_AND_: KEY_ID.KEYBOARD_0,
    KEYBOARD_HID_USAGE.KEYBOARD_GRAVE_ACCENT_AND_TILDE: KEY_ID.KEYBOARD_GRAVE_ACCENT_AND_TILDE,
    KEYBOARD_HID_USAGE.KEYBOARD_TAB: KEY_ID.KEYBOARD_TAB,
    KEYBOARD_HID_USAGE.KEYBOARD_CAPS_LOCK: KEY_ID.KEYBOARD_CAPS_LOCK,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFTSHIFT: KEY_ID.KEYBOARD_LEFT_SHIFT,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFT_CONTROL: KEY_ID.KEYBOARD_LEFT_CONTROL,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFT_GUI: KEY_ID.KEYBOARD_LEFT_WIN_OR_OPTION,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFT_ALT: KEY_ID.KEYBOARD_LEFT_ALT,
    KEYBOARD_HID_USAGE.KEYBOARD_SPACE_BAR: KEY_ID.KEYBOARD_SPACE_BAR,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_ALT: KEY_ID.KEYBOARD_RIGHT_ALT,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_GUI: KEY_ID.KEYBOARD_RIGHT_WIN_OR_OPTION,
    KEYBOARD_HID_USAGE.KEYBOARD_MENU: KEY_ID.KEYBOARD_MENU,
    KEYBOARD_HID_USAGE.KEYBOARD_APPLICATION: KEY_ID.CONTEXTUAL_MENU,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_CONTROL: KEY_ID.KEYBOARD_RIGHT_CONTROL,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHTSHIFT: KEY_ID.KEYBOARD_RIGHT_SHIFT,
    KEYBOARD_HID_USAGE.KEYBOARD_RETURN_ENTER: KEY_ID.KEYBOARD_RETURN_ENTER,
    KEYBOARD_HID_USAGE.KEYBOARD_BACKSLASH_AND_PIPE: KEY_ID.KEYBOARD_BACKSLASH_AND_PIPE,
    KEYBOARD_HID_USAGE.KEYBOARD_DELETE_BACKSPACE: KEY_ID.KEYBOARD_BACKSPACE,
    KEYBOARD_HID_USAGE.KEYBOARD_EQUAL_AND_PLUS: KEY_ID.KEYBOARD_EQUAL_AND_PLUS,
    KEYBOARD_HID_USAGE.KEYBOARD_DASH_AND_UNDERSCORE: KEY_ID.KEYBOARD_DASH_AND_UNDERSCORE,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFT_BRACKET_AND_BRACE: KEY_ID.KEYBOARD_LEFT_BRACKET_AND_BRACE,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_BRACKET_AND_BRACE: KEY_ID.KEYBOARD_RIGHT_BRACKET_AND_BRACE,
    KEYBOARD_HID_USAGE.KEYBOARD_SEMICOLON_AND_COLON: KEY_ID.KEYBOARD_SEMICOLON_AND_COLON,
    KEYBOARD_HID_USAGE.KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK: KEY_ID.KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK,
    KEYBOARD_HID_USAGE.KEYBOARD_COMMA_AND_LESS: KEY_ID.KEYBOARD_COMMA_AND_LESS,
    KEYBOARD_HID_USAGE.KEYBOARD_PERIOD_AND_MORE: KEY_ID.KEYBOARD_PERIOD_AND_MORE,
    KEYBOARD_HID_USAGE.KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK: KEY_ID.KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK,
    KEYBOARD_HID_USAGE.KEYBOARD_INSERT: KEY_ID.KEYBOARD_INSERT,
    KEYBOARD_HID_USAGE.KEYBOARD_HOME: KEY_ID.KEYBOARD_HOME,
    KEYBOARD_HID_USAGE.KEYBOARD_PAGE_UP: KEY_ID.KEYBOARD_PAGE_UP,
    KEYBOARD_HID_USAGE.KEYBOARD_DELETE_FORWARD: KEY_ID.KEYBOARD_DELETE_FORWARD,
    KEYBOARD_HID_USAGE.KEYBOARD_END: KEY_ID.KEYBOARD_END,
    KEYBOARD_HID_USAGE.KEYBOARD_PAGE_DOWN: KEY_ID.KEYBOARD_PAGE_DOWN,
    KEYBOARD_HID_USAGE.KEYBOARD_UP_ARROW: KEY_ID.KEYBOARD_UP_ARROW,
    KEYBOARD_HID_USAGE.KEYBOARD_LEFT_ARROW: KEY_ID.KEYBOARD_LEFT_ARROW,
    KEYBOARD_HID_USAGE.KEYBOARD_DOWN_ARROW: KEY_ID.KEYBOARD_DOWN_ARROW,
    KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_ARROW: KEY_ID.KEYBOARD_RIGHT_ARROW,
    KEYBOARD_HID_USAGE.KEYBOARD_ESCAPE: KEY_ID.KEYBOARD_ESCAPE,
    KEYBOARD_HID_USAGE.KEYBOARD_F1: KEY_ID.KEYBOARD_F1,
    KEYBOARD_HID_USAGE.KEYBOARD_F2: KEY_ID.KEYBOARD_F2,
    KEYBOARD_HID_USAGE.KEYBOARD_F3: KEY_ID.KEYBOARD_F3,
    KEYBOARD_HID_USAGE.KEYBOARD_F4: KEY_ID.KEYBOARD_F4,
    KEYBOARD_HID_USAGE.KEYBOARD_F5: KEY_ID.KEYBOARD_F5,
    KEYBOARD_HID_USAGE.KEYBOARD_F6: KEY_ID.KEYBOARD_F6,
    KEYBOARD_HID_USAGE.KEYBOARD_F7: KEY_ID.KEYBOARD_F7,
    KEYBOARD_HID_USAGE.KEYBOARD_F8: KEY_ID.KEYBOARD_F8,
    KEYBOARD_HID_USAGE.KEYBOARD_F9: KEY_ID.KEYBOARD_F9,
    KEYBOARD_HID_USAGE.KEYBOARD_F10: KEY_ID.KEYBOARD_F10,
    KEYBOARD_HID_USAGE.KEYBOARD_F11: KEY_ID.KEYBOARD_F11,
    KEYBOARD_HID_USAGE.KEYBOARD_F12: KEY_ID.KEYBOARD_F12,
    KEYBOARD_HID_USAGE.KEYBOARD_F13: KEY_ID.KEYBOARD_F13,
    KEYBOARD_HID_USAGE.KEYBOARD_F14: KEY_ID.KEYBOARD_F14,
    KEYBOARD_HID_USAGE.KEYBOARD_F15: KEY_ID.KEYBOARD_F15,
    KEYBOARD_HID_USAGE.KEYBOARD_F16: KEY_ID.KEYBOARD_F16,
    KEYBOARD_HID_USAGE.KEYBOARD_F17: KEY_ID.KEYBOARD_F17,
    KEYBOARD_HID_USAGE.KEYBOARD_F18: KEY_ID.KEYBOARD_F18,
    KEYBOARD_HID_USAGE.KEYBOARD_F19: KEY_ID.KEYBOARD_F19,
    KEYBOARD_HID_USAGE.KEYBOARD_F20: KEY_ID.KEYBOARD_F20,
    KEYBOARD_HID_USAGE.KEYBOARD_F21: KEY_ID.KEYBOARD_F21,
    KEYBOARD_HID_USAGE.KEYBOARD_F22: KEY_ID.KEYBOARD_F22,
    KEYBOARD_HID_USAGE.KEYBOARD_F23: KEY_ID.KEYBOARD_F23,
    KEYBOARD_HID_USAGE.KEYBOARD_F24: KEY_ID.KEYBOARD_F24,
    KEYBOARD_HID_USAGE.KEYPAD_NUM_LOCK_AND_CLEAR: KEY_ID.KEYPAD_NUM_LOCK_AND_CLEAR,
    KEYBOARD_HID_USAGE.KEYPAD_FORWARD_SLASH: KEY_ID.KEYPAD_FORWARD_SLASH,
    KEYBOARD_HID_USAGE.KEYPAD_ASTERISK: KEY_ID.KEYPAD_ASTERISK,
    KEYBOARD_HID_USAGE.KEYPAD_DASH: KEY_ID.KEYPAD_MINUS,
    KEYBOARD_HID_USAGE.KEYPAD_PLUS: KEY_ID.KEYPAD_PLUS,
    KEYBOARD_HID_USAGE.KEYPAD_ENTER: KEY_ID.KEYPAD_ENTER,
    KEYBOARD_HID_USAGE.KEYPAD_COMMA_AND_DELETE: KEY_ID.KEYPAD_PERIOD_AND_DELETE,
    KEYBOARD_HID_USAGE.KEYPAD_1_AND_END: KEY_ID.KEYPAD_1_AND_END,
    KEYBOARD_HID_USAGE.KEYPAD_2_AND_DOWN_ARROW: KEY_ID.KEYPAD_2_AND_DOWN_ARROW,
    KEYBOARD_HID_USAGE.KEYPAD_3_AND_PAGE_DN: KEY_ID.KEYPAD_3_AND_PAGE_DN,
    KEYBOARD_HID_USAGE.KEYPAD_4_AND_LEFT_ARROW: KEY_ID.KEYPAD_4_AND_LEFT_ARROW,
    KEYBOARD_HID_USAGE.KEYPAD_5: KEY_ID.KEYPAD_5,
    KEYBOARD_HID_USAGE.KEYPAD_6_AND_RIGHT_ARROW: KEY_ID.KEYPAD_6_AND_RIGHT_ARROW,
    KEYBOARD_HID_USAGE.KEYPAD_7_AND_HOME: KEY_ID.KEYPAD_7_AND_HOME,
    KEYBOARD_HID_USAGE.KEYPAD_8_AND_UP_ARROW: KEY_ID.KEYPAD_8_AND_UP_ARROW,
    KEYBOARD_HID_USAGE.KEYPAD_9_AND_PAGE_UP: KEY_ID.KEYPAD_9_AND_PAGE_UP,
    KEYBOARD_HID_USAGE.KEYPAD_0_AND_INSERT: KEY_ID.KEYPAD_0_AND_INSERT,
    KEYBOARD_HID_USAGE.KEYBOARD_PRINT_SCREEN: KEY_ID.KEYBOARD_PRINT_SCREEN,
    KEYBOARD_HID_USAGE.KEYBOARD_SCROLL_LOCK: KEY_ID.KEYBOARD_SCROLL_LOCK,
    KEYBOARD_HID_USAGE.KEYBOARD_PAUSE: KEY_ID.KEYBOARD_PAUSE,
    KEYBOARD_HID_USAGE.KEYBOARD_NON_US_AND_TILDE: KEY_ID.KEYBOARD_NON_US_AND_TILDE,
    KEYBOARD_HID_USAGE.KEYBOARD_NON_US_BACKSLASH_AND_PIPE: KEY_ID.KEYBOARD_NON_US_BACKSLASH_AND_PIPE,
    KEYBOARD_HID_USAGE.KEYBOARD_POWER: KEY_ID.KEYBOARD_POWER,
    KEYBOARD_HID_USAGE.KEYBOARD_EXECUTE: KEY_ID.KEYBOARD_EXECUTE,
    KEYBOARD_HID_USAGE.KEYBOARD_HELP: KEY_ID.KEYBOARD_HELP,
    KEYBOARD_HID_USAGE.KEYBOARD_SELECT: KEY_ID.KEYBOARD_SELECT,
    KEYBOARD_HID_USAGE.KEYBOARD_STOP: KEY_ID.KEYBOARD_STOP,
    KEYBOARD_HID_USAGE.KEYBOARD_AGAIN: KEY_ID.KEYBOARD_AGAIN,
    KEYBOARD_HID_USAGE.KEYBOARD_UNDO: KEY_ID.KEYBOARD_UNDO,
    KEYBOARD_HID_USAGE.KEYBOARD_CUT: KEY_ID.KEYBOARD_CUT,
    KEYBOARD_HID_USAGE.KEYBOARD_COPY: KEY_ID.KEYBOARD_COPY,
    KEYBOARD_HID_USAGE.KEYBOARD_PASTE: KEY_ID.KEYBOARD_PASTE,
    KEYBOARD_HID_USAGE.KEYBOARD_FIND: KEY_ID.KEYBOARD_FIND,
    KEYBOARD_HID_USAGE.KEYBOARD_MUTE: KEY_ID.KEYBOARD_MUTE,
    KEYBOARD_HID_USAGE.KEYBOARD_VOLUME_UP: KEY_ID.KEYBOARD_VOLUME_UP,
    KEYBOARD_HID_USAGE.KEYBOARD_VOLUME_DOWN: KEY_ID.KEYBOARD_VOLUME_DOWN,
    KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_CAPS_LOCK: KEY_ID.KEYBOARD_LOCKING_CAPS_LOCK,
    KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_NUM_LOCK: KEY_ID.KEYBOARD_LOCKING_NUM_LOCK,
    KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_SCROLL_LOCK: KEY_ID.KEYBOARD_LOCKING_SCROLL_LOCK,
    KEYBOARD_HID_USAGE.KEYPAD_COMMA: KEY_ID.KEYPAD_COMMA,
    KEYBOARD_HID_USAGE.KEYPAD_EQUAL_SIGN: KEY_ID.KEYPAD_EQUAL_SIGN,
    KEYBOARD_HID_USAGE.KEYPAD_EQUAL: KEY_ID.KEYPAD_EQUAL,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL1: KEY_ID.KEYBOARD_INTERNATIONAL1,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL2: KEY_ID.KEYBOARD_INTERNATIONAL2,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL3: KEY_ID.KEYBOARD_INTERNATIONAL3,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL4: KEY_ID.KEYBOARD_INTERNATIONAL4,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL5: KEY_ID.KEYBOARD_INTERNATIONAL5,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL6: KEY_ID.KEYBOARD_INTERNATIONAL6,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL7: KEY_ID.KEYBOARD_INTERNATIONAL7,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL8: KEY_ID.KEYBOARD_INTERNATIONAL8,
    KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL9: KEY_ID.KEYBOARD_INTERNATIONAL9,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG1: KEY_ID.KEYBOARD_LANG1,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG2: KEY_ID.KEYBOARD_LANG2,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG3: KEY_ID.KEYBOARD_LANG3,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG4: KEY_ID.KEYBOARD_LANG4,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG5: KEY_ID.KEYBOARD_LANG5,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG6: KEY_ID.KEYBOARD_LANG6,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG7: KEY_ID.KEYBOARD_LANG7,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG8: KEY_ID.KEYBOARD_LANG8,
    KEYBOARD_HID_USAGE.KEYBOARD_LANG9: KEY_ID.KEYBOARD_LANG9,
    KEYBOARD_HID_USAGE.KEYBOARD_ALTERNATE_ERASE: KEY_ID.KEYBOARD_ALTERNATE_ERASE,
    KEYBOARD_HID_USAGE.KEYBOARD_CANCEL: KEY_ID.KEYBOARD_CANCEL,
    KEYBOARD_HID_USAGE.KEYBOARD_CLEAR: KEY_ID.KEYBOARD_CLEAR,
    KEYBOARD_HID_USAGE.KEYBOARD_PRIOR: KEY_ID.KEYBOARD_PRIOR,
    KEYBOARD_HID_USAGE.KEYBOARD_RETURN: KEY_ID.KEYBOARD_RETURN,
    KEYBOARD_HID_USAGE.KEYBOARD_SEPARATOR: KEY_ID.KEYBOARD_SEPARATOR,
    KEYBOARD_HID_USAGE.KEYBOARD_OUT: KEY_ID.KEYBOARD_OUT,
    KEYBOARD_HID_USAGE.KEYBOARD_OPER: KEY_ID.KEYBOARD_OPER,
    KEYBOARD_HID_USAGE.KEYBOARD_CLEAR_AGAIN: KEY_ID.KEYBOARD_CLEAR_AGAIN,

}

STANDARD_KEYS = {
    KEY_ID.KEYBOARD_A: KEYBOARD_HID_USAGE.KEYBOARD_A_AND_A,
    KEY_ID.KEYBOARD_B: KEYBOARD_HID_USAGE.KEYBOARD_B_AND_B,
    KEY_ID.KEYBOARD_C: KEYBOARD_HID_USAGE.KEYBOARD_C_AND_C,
    KEY_ID.KEYBOARD_D: KEYBOARD_HID_USAGE.KEYBOARD_D_AND_D,
    KEY_ID.KEYBOARD_E: KEYBOARD_HID_USAGE.KEYBOARD_E_AND_E,
    KEY_ID.KEYBOARD_F: KEYBOARD_HID_USAGE.KEYBOARD_F_AND_F,
    KEY_ID.KEYBOARD_G: KEYBOARD_HID_USAGE.KEYBOARD_G_AND_G,
    KEY_ID.KEYBOARD_H: KEYBOARD_HID_USAGE.KEYBOARD_H_AND_H,
    KEY_ID.KEYBOARD_I: KEYBOARD_HID_USAGE.KEYBOARD_I_AND_I,
    KEY_ID.KEYBOARD_J: KEYBOARD_HID_USAGE.KEYBOARD_J_AND_J,
    KEY_ID.KEYBOARD_K: KEYBOARD_HID_USAGE.KEYBOARD_K_AND_K,
    KEY_ID.KEYBOARD_L: KEYBOARD_HID_USAGE.KEYBOARD_L_AND_L,
    KEY_ID.KEYBOARD_M: KEYBOARD_HID_USAGE.KEYBOARD_M_AND_M,
    KEY_ID.KEYBOARD_N: KEYBOARD_HID_USAGE.KEYBOARD_N_AND_N,
    KEY_ID.KEYBOARD_O: KEYBOARD_HID_USAGE.KEYBOARD_O_AND_O,
    KEY_ID.KEYBOARD_P: KEYBOARD_HID_USAGE.KEYBOARD_P_AND_P,
    KEY_ID.KEYBOARD_Q: KEYBOARD_HID_USAGE.KEYBOARD_Q_AND_Q,
    KEY_ID.KEYBOARD_R: KEYBOARD_HID_USAGE.KEYBOARD_R_AND_R,
    KEY_ID.KEYBOARD_S: KEYBOARD_HID_USAGE.KEYBOARD_S_AND_S,
    KEY_ID.KEYBOARD_T: KEYBOARD_HID_USAGE.KEYBOARD_T_AND_T,
    KEY_ID.KEYBOARD_U: KEYBOARD_HID_USAGE.KEYBOARD_U_AND_U,
    KEY_ID.KEYBOARD_V: KEYBOARD_HID_USAGE.KEYBOARD_V_AND_V,
    KEY_ID.KEYBOARD_W: KEYBOARD_HID_USAGE.KEYBOARD_W_AND_W,
    KEY_ID.KEYBOARD_X: KEYBOARD_HID_USAGE.KEYBOARD_X_AND_X,
    KEY_ID.KEYBOARD_Y: KEYBOARD_HID_USAGE.KEYBOARD_Y_AND_Y,
    KEY_ID.KEYBOARD_Z: KEYBOARD_HID_USAGE.KEYBOARD_Z_AND_Z,
    KEY_ID.KEYBOARD_1: KEYBOARD_HID_USAGE.KEYBOARD_1_AND_,
    KEY_ID.KEYBOARD_2: KEYBOARD_HID_USAGE.KEYBOARD_2_AND_,
    KEY_ID.KEYBOARD_3: KEYBOARD_HID_USAGE.KEYBOARD_3_AND_,
    KEY_ID.KEYBOARD_4: KEYBOARD_HID_USAGE.KEYBOARD_4_AND_,
    KEY_ID.KEYBOARD_5: KEYBOARD_HID_USAGE.KEYBOARD_5_AND_,
    KEY_ID.KEYBOARD_6: KEYBOARD_HID_USAGE.KEYBOARD_6_AND_,
    KEY_ID.KEYBOARD_7: KEYBOARD_HID_USAGE.KEYBOARD_7_AND_,
    KEY_ID.KEYBOARD_8: KEYBOARD_HID_USAGE.KEYBOARD_8_AND_,
    KEY_ID.KEYBOARD_9: KEYBOARD_HID_USAGE.KEYBOARD_9_AND_,
    KEY_ID.KEYBOARD_0: KEYBOARD_HID_USAGE.KEYBOARD_0_AND_,
    KEY_ID.KEYBOARD_GRAVE_ACCENT_AND_TILDE: KEYBOARD_HID_USAGE.KEYBOARD_GRAVE_ACCENT_AND_TILDE,
    KEY_ID.KEYBOARD_TAB: KEYBOARD_HID_USAGE.KEYBOARD_TAB,
    KEY_ID.KEYBOARD_CAPS_LOCK: KEYBOARD_HID_USAGE.KEYBOARD_CAPS_LOCK,
    KEY_ID.KEYBOARD_LEFT_SHIFT: KEYBOARD_HID_USAGE.KEYBOARD_LEFTSHIFT,
    KEY_ID.KEYBOARD_LEFT_CONTROL: KEYBOARD_HID_USAGE.KEYBOARD_LEFT_CONTROL,
    KEY_ID.KEYBOARD_LEFT_WIN_OR_OPTION: KEYBOARD_HID_USAGE.KEYBOARD_LEFT_GUI,
    KEY_ID.KEYBOARD_LEFT_ALT: KEYBOARD_HID_USAGE.KEYBOARD_LEFT_ALT,
    KEY_ID.KEYBOARD_SPACE_BAR: KEYBOARD_HID_USAGE.KEYBOARD_SPACE_BAR,
    KEY_ID.KEYBOARD_RIGHT_ALT: KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_ALT,
    KEY_ID.CONTEXTUAL_MENU: KEYBOARD_HID_USAGE.KEYBOARD_APPLICATION,
    KEY_ID.KEYBOARD_RIGHT_CONTROL: KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_CONTROL,
    KEY_ID.KEYBOARD_RIGHT_SHIFT: KEYBOARD_HID_USAGE.KEYBOARD_RIGHTSHIFT,
    KEY_ID.KEYBOARD_RETURN_ENTER: KEYBOARD_HID_USAGE.KEYBOARD_RETURN_ENTER,
    KEY_ID.KEYBOARD_BACKSLASH_AND_PIPE: KEYBOARD_HID_USAGE.KEYBOARD_BACKSLASH_AND_PIPE,
    KEY_ID.KEYBOARD_BACKSPACE: KEYBOARD_HID_USAGE.KEYBOARD_DELETE_BACKSPACE,
    KEY_ID.KEYBOARD_EQUAL_AND_PLUS: KEYBOARD_HID_USAGE.KEYBOARD_EQUAL_AND_PLUS,
    KEY_ID.KEYBOARD_DASH_AND_UNDERSCORE: KEYBOARD_HID_USAGE.KEYBOARD_DASH_AND_UNDERSCORE,
    KEY_ID.KEYBOARD_LEFT_BRACKET_AND_BRACE: KEYBOARD_HID_USAGE.KEYBOARD_LEFT_BRACKET_AND_BRACE,
    KEY_ID.KEYBOARD_RIGHT_BRACKET_AND_BRACE: KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_BRACKET_AND_BRACE,
    KEY_ID.KEYBOARD_SEMICOLON_AND_COLON: KEYBOARD_HID_USAGE.KEYBOARD_SEMICOLON_AND_COLON,
    KEY_ID.KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK: KEYBOARD_HID_USAGE.KEYBOARD_APOSTROPHE_AND_QUOTATION_MARK,
    KEY_ID.KEYBOARD_COMMA_AND_LESS: KEYBOARD_HID_USAGE.KEYBOARD_COMMA_AND_LESS,
    KEY_ID.KEYBOARD_PERIOD_AND_MORE: KEYBOARD_HID_USAGE.KEYBOARD_PERIOD_AND_MORE,
    KEY_ID.KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK: KEYBOARD_HID_USAGE.KEYBOARD_FORWARD_SLASH_AND_QUESTION_MARK,
    KEY_ID.KEYBOARD_INSERT: KEYBOARD_HID_USAGE.KEYBOARD_INSERT,
    KEY_ID.KEYBOARD_HOME: KEYBOARD_HID_USAGE.KEYBOARD_HOME,
    KEY_ID.KEYBOARD_PAGE_UP: KEYBOARD_HID_USAGE.KEYBOARD_PAGE_UP,
    KEY_ID.KEYBOARD_DELETE_FORWARD: KEYBOARD_HID_USAGE.KEYBOARD_DELETE_FORWARD,
    KEY_ID.KEYBOARD_END: KEYBOARD_HID_USAGE.KEYBOARD_END,
    KEY_ID.KEYBOARD_PAGE_DOWN: KEYBOARD_HID_USAGE.KEYBOARD_PAGE_DOWN,
    KEY_ID.KEYBOARD_UP_ARROW: KEYBOARD_HID_USAGE.KEYBOARD_UP_ARROW,
    KEY_ID.KEYBOARD_LEFT_ARROW: KEYBOARD_HID_USAGE.KEYBOARD_LEFT_ARROW,
    KEY_ID.KEYBOARD_DOWN_ARROW: KEYBOARD_HID_USAGE.KEYBOARD_DOWN_ARROW,
    KEY_ID.KEYBOARD_RIGHT_ARROW: KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_ARROW,
    KEY_ID.KEYBOARD_ESCAPE: KEYBOARD_HID_USAGE.KEYBOARD_ESCAPE,
    KEY_ID.KEYBOARD_F1: KEYBOARD_HID_USAGE.KEYBOARD_F1,
    KEY_ID.KEYBOARD_F2: KEYBOARD_HID_USAGE.KEYBOARD_F2,
    KEY_ID.KEYBOARD_F3: KEYBOARD_HID_USAGE.KEYBOARD_F3,
    KEY_ID.KEYBOARD_F4: KEYBOARD_HID_USAGE.KEYBOARD_F4,
    KEY_ID.KEYBOARD_F5: KEYBOARD_HID_USAGE.KEYBOARD_F5,
    KEY_ID.KEYBOARD_F6: KEYBOARD_HID_USAGE.KEYBOARD_F6,
    KEY_ID.KEYBOARD_F7: KEYBOARD_HID_USAGE.KEYBOARD_F7,
    KEY_ID.KEYBOARD_F8: KEYBOARD_HID_USAGE.KEYBOARD_F8,
    KEY_ID.KEYBOARD_F9: KEYBOARD_HID_USAGE.KEYBOARD_F9,
    KEY_ID.KEYBOARD_F10: KEYBOARD_HID_USAGE.KEYBOARD_F10,
    KEY_ID.KEYBOARD_F11: KEYBOARD_HID_USAGE.KEYBOARD_F11,
    KEY_ID.KEYBOARD_F12: KEYBOARD_HID_USAGE.KEYBOARD_F12,
    KEY_ID.KEYPAD_NUM_LOCK_AND_CLEAR: KEYBOARD_HID_USAGE.KEYPAD_NUM_LOCK_AND_CLEAR,
    KEY_ID.KEYPAD_FORWARD_SLASH: KEYBOARD_HID_USAGE.KEYPAD_FORWARD_SLASH,
    KEY_ID.KEYPAD_ASTERISK: KEYBOARD_HID_USAGE.KEYPAD_ASTERISK,
    KEY_ID.KEYPAD_MINUS: KEYBOARD_HID_USAGE.KEYPAD_DASH,
    KEY_ID.KEYPAD_PLUS: KEYBOARD_HID_USAGE.KEYPAD_PLUS,
    KEY_ID.KEYPAD_ENTER: KEYBOARD_HID_USAGE.KEYPAD_ENTER,
    KEY_ID.KEYPAD_PERIOD_AND_DELETE: KEYBOARD_HID_USAGE.KEYPAD_COMMA_AND_DELETE,
    KEY_ID.KEYPAD_1_AND_END: KEYBOARD_HID_USAGE.KEYPAD_1_AND_END,
    KEY_ID.KEYPAD_2_AND_DOWN_ARROW: KEYBOARD_HID_USAGE.KEYPAD_2_AND_DOWN_ARROW,
    KEY_ID.KEYPAD_3_AND_PAGE_DN: KEYBOARD_HID_USAGE.KEYPAD_3_AND_PAGE_DN,
    KEY_ID.KEYPAD_4_AND_LEFT_ARROW: KEYBOARD_HID_USAGE.KEYPAD_4_AND_LEFT_ARROW,
    KEY_ID.KEYPAD_5: KEYBOARD_HID_USAGE.KEYPAD_5,
    KEY_ID.KEYPAD_6_AND_RIGHT_ARROW: KEYBOARD_HID_USAGE.KEYPAD_6_AND_RIGHT_ARROW,
    KEY_ID.KEYPAD_7_AND_HOME: KEYBOARD_HID_USAGE.KEYPAD_7_AND_HOME,
    KEY_ID.KEYPAD_8_AND_UP_ARROW: KEYBOARD_HID_USAGE.KEYPAD_8_AND_UP_ARROW,
    KEY_ID.KEYPAD_9_AND_PAGE_UP: KEYBOARD_HID_USAGE.KEYPAD_9_AND_PAGE_UP,
    KEY_ID.KEYPAD_0_AND_INSERT: KEYBOARD_HID_USAGE.KEYPAD_0_AND_INSERT,
    KEY_ID.KEYBOARD_PRINT_SCREEN: KEYBOARD_HID_USAGE.KEYBOARD_PRINT_SCREEN,
    KEY_ID.KEYBOARD_SCROLL_LOCK: KEYBOARD_HID_USAGE.KEYBOARD_SCROLL_LOCK,
    KEY_ID.KEYBOARD_PAUSE: KEYBOARD_HID_USAGE.KEYBOARD_PAUSE
}

ALL_KEYS = {
    **STANDARD_KEYS,
    KEY_ID.KEYBOARD_NON_US_AND_TILDE: KEYBOARD_HID_USAGE.KEYBOARD_NON_US_AND_TILDE,
    KEY_ID.KEYBOARD_NON_US_BACKSLASH_AND_PIPE: KEYBOARD_HID_USAGE.KEYBOARD_NON_US_BACKSLASH_AND_PIPE,
    KEY_ID.KEYBOARD_POWER: KEYBOARD_HID_USAGE.KEYBOARD_POWER,
    KEY_ID.KEYPAD_EQUAL: KEYBOARD_HID_USAGE.KEYPAD_EQUAL,
    KEY_ID.KEYBOARD_F13: KEYBOARD_HID_USAGE.KEYBOARD_F13,
    KEY_ID.KEYBOARD_F14: KEYBOARD_HID_USAGE.KEYBOARD_F14,
    KEY_ID.KEYBOARD_F15: KEYBOARD_HID_USAGE.KEYBOARD_F15,
    KEY_ID.KEYBOARD_F16: KEYBOARD_HID_USAGE.KEYBOARD_F16,
    KEY_ID.KEYBOARD_F17: KEYBOARD_HID_USAGE.KEYBOARD_F17,
    KEY_ID.KEYBOARD_F18: KEYBOARD_HID_USAGE.KEYBOARD_F18,
    KEY_ID.KEYBOARD_F19: KEYBOARD_HID_USAGE.KEYBOARD_F19,
    KEY_ID.KEYBOARD_F20: KEYBOARD_HID_USAGE.KEYBOARD_F20,
    KEY_ID.KEYBOARD_F21: KEYBOARD_HID_USAGE.KEYBOARD_F21,
    KEY_ID.KEYBOARD_F22: KEYBOARD_HID_USAGE.KEYBOARD_F22,
    KEY_ID.KEYBOARD_F23: KEYBOARD_HID_USAGE.KEYBOARD_F23,
    KEY_ID.KEYBOARD_F24: KEYBOARD_HID_USAGE.KEYBOARD_F24,
    KEY_ID.KEYBOARD_EXECUTE: KEYBOARD_HID_USAGE.KEYBOARD_EXECUTE,
    KEY_ID.KEYBOARD_HELP: KEYBOARD_HID_USAGE.KEYBOARD_HELP,
    KEY_ID.KEYBOARD_SELECT: KEYBOARD_HID_USAGE.KEYBOARD_SELECT,
    KEY_ID.KEYBOARD_STOP: KEYBOARD_HID_USAGE.KEYBOARD_STOP,
    KEY_ID.KEYBOARD_AGAIN: KEYBOARD_HID_USAGE.KEYBOARD_AGAIN,
    KEY_ID.KEYBOARD_UNDO: KEYBOARD_HID_USAGE.KEYBOARD_UNDO,
    KEY_ID.KEYBOARD_CUT: KEYBOARD_HID_USAGE.KEYBOARD_CUT,
    KEY_ID.KEYBOARD_COPY: KEYBOARD_HID_USAGE.KEYBOARD_COPY,
    KEY_ID.KEYBOARD_PASTE: KEYBOARD_HID_USAGE.KEYBOARD_PASTE,
    KEY_ID.KEYBOARD_FIND: KEYBOARD_HID_USAGE.KEYBOARD_FIND,
    KEY_ID.KEYBOARD_MUTE: KEYBOARD_HID_USAGE.KEYBOARD_MUTE,
    KEY_ID.KEYBOARD_VOLUME_UP: KEYBOARD_HID_USAGE.KEYBOARD_VOLUME_UP,
    KEY_ID.KEYBOARD_VOLUME_DOWN: KEYBOARD_HID_USAGE.KEYBOARD_VOLUME_DOWN,
    KEY_ID.KEYBOARD_LOCKING_CAPS_LOCK: KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_CAPS_LOCK,
    KEY_ID.KEYBOARD_LOCKING_NUM_LOCK: KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_NUM_LOCK,
    KEY_ID.KEYBOARD_LOCKING_SCROLL_LOCK: KEYBOARD_HID_USAGE.KEYBOARD_LOCKING_SCROLL_LOCK,
    KEY_ID.KEYPAD_COMMA: KEYBOARD_HID_USAGE.KEYPAD_COMMA,
    KEY_ID.KEYPAD_EQUAL_SIGN: KEYBOARD_HID_USAGE.KEYPAD_EQUAL_SIGN,
    KEY_ID.KEYBOARD_INTERNATIONAL1: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL1,
    KEY_ID.KEYBOARD_INTERNATIONAL2: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL2,
    KEY_ID.KEYBOARD_INTERNATIONAL3: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL3,
    KEY_ID.KEYBOARD_INTERNATIONAL4: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL4,
    KEY_ID.KEYBOARD_INTERNATIONAL5: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL5,
    KEY_ID.KEYBOARD_INTERNATIONAL6: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL6,
    KEY_ID.KEYBOARD_INTERNATIONAL7: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL7,
    KEY_ID.KEYBOARD_INTERNATIONAL8: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL8,
    KEY_ID.KEYBOARD_INTERNATIONAL9: KEYBOARD_HID_USAGE.KEYBOARD_INTERNATIONAL9,
    KEY_ID.KEYBOARD_LANG1: KEYBOARD_HID_USAGE.KEYBOARD_LANG1,
    KEY_ID.KEYBOARD_LANG2: KEYBOARD_HID_USAGE.KEYBOARD_LANG2,
    KEY_ID.KEYBOARD_LANG3: KEYBOARD_HID_USAGE.KEYBOARD_LANG3,
    KEY_ID.KEYBOARD_LANG4: KEYBOARD_HID_USAGE.KEYBOARD_LANG4,
    KEY_ID.KEYBOARD_LANG5: KEYBOARD_HID_USAGE.KEYBOARD_LANG5,
    KEY_ID.KEYBOARD_LANG6: KEYBOARD_HID_USAGE.KEYBOARD_LANG6,
    KEY_ID.KEYBOARD_LANG7: KEYBOARD_HID_USAGE.KEYBOARD_LANG7,
    KEY_ID.KEYBOARD_LANG8: KEYBOARD_HID_USAGE.KEYBOARD_LANG8,
    KEY_ID.KEYBOARD_LANG9: KEYBOARD_HID_USAGE.KEYBOARD_LANG9,
    KEY_ID.KEYBOARD_ALTERNATE_ERASE: KEYBOARD_HID_USAGE.KEYBOARD_ALTERNATE_ERASE,
    KEY_ID.KEYBOARD_SYS_REQ_ATTENTION: KEYBOARD_HID_USAGE.KEYBOARD_SYS_REQ_ATTENTION,
    KEY_ID.KEYBOARD_CANCEL: KEYBOARD_HID_USAGE.KEYBOARD_CANCEL,
    KEY_ID.KEYBOARD_CLEAR: KEYBOARD_HID_USAGE.KEYBOARD_CLEAR,
    KEY_ID.KEYBOARD_PRIOR: KEYBOARD_HID_USAGE.KEYBOARD_PRIOR,
    KEY_ID.KEYBOARD_RETURN: KEYBOARD_HID_USAGE.KEYBOARD_RETURN,
    KEY_ID.KEYBOARD_SEPARATOR: KEYBOARD_HID_USAGE.KEYBOARD_SEPARATOR,
    KEY_ID.KEYBOARD_OUT: KEYBOARD_HID_USAGE.KEYBOARD_OUT,
    KEY_ID.KEYBOARD_OPER: KEYBOARD_HID_USAGE.KEYBOARD_OPER,
    KEY_ID.KEYBOARD_CLEAR_AGAIN: KEYBOARD_HID_USAGE.KEYBOARD_CLEAR_AGAIN,
    KEY_ID.KEYBOARD_CRSEL_PROPS: KEYBOARD_HID_USAGE.KEYBOARD_CRSEL_PROPS,
    KEY_ID.KEYBOARD_EXSEL: KEYBOARD_HID_USAGE.KEYBOARD_EXSEL,
    KEY_ID.KEYPAD_00: KEYBOARD_HID_USAGE.KEYPAD_00,
    KEY_ID.KEYPAD_000: KEYBOARD_HID_USAGE.KEYPAD_000,
    KEY_ID.THOUSANDS_SEPARATOR: KEYBOARD_HID_USAGE.THOUSANDS_SEPARATOR,
    KEY_ID.DECIMAL_SEPARATOR: KEYBOARD_HID_USAGE.DECIMAL_SEPARATOR,
    KEY_ID.CURRENCY_UNIT: KEYBOARD_HID_USAGE.CURRENCY_UNIT,
    KEY_ID.CURRENCY_SUB_UNIT: KEYBOARD_HID_USAGE.CURRENCY_SUB_UNIT,
    KEY_ID.KEYPAD_RIGHT_PARENTHESES: KEYBOARD_HID_USAGE.KEYPAD_RIGHT_PARENTHESES,
    KEY_ID.KEYPAD_LEFT_PARENTHESES: KEYBOARD_HID_USAGE.KEYPAD_LEFT_PARENTHESES,
    KEY_ID.KEYPAD_RIGHT_BRACE: KEYBOARD_HID_USAGE.KEYPAD_RIGHT_BRACE,
    KEY_ID.KEYPAD_LEFT_BRACE: KEYBOARD_HID_USAGE.KEYPAD_LEFT_BRACE,
    KEY_ID.KEYPAD_TAB: KEYBOARD_HID_USAGE.KEYPAD_TAB,
    KEY_ID.KEYPAD_BACKSPACE: KEYBOARD_HID_USAGE.KEYPAD_BACKSPACE,
    KEY_ID.KEYPAD_A: KEYBOARD_HID_USAGE.KEYPAD_A,
    KEY_ID.KEYPAD_B: KEYBOARD_HID_USAGE.KEYPAD_B,
    KEY_ID.KEYPAD_C: KEYBOARD_HID_USAGE.KEYPAD_C,
    KEY_ID.KEYPAD_D: KEYBOARD_HID_USAGE.KEYPAD_D,
    KEY_ID.KEYPAD_E: KEYBOARD_HID_USAGE.KEYPAD_E,
    KEY_ID.KEYPAD_F: KEYBOARD_HID_USAGE.KEYPAD_F,
    KEY_ID.KEYPAD_XOR: KEYBOARD_HID_USAGE.KEYPAD_XOR,
    KEY_ID.KEYPAD_CARET: KEYBOARD_HID_USAGE.KEYPAD_CARET,
    KEY_ID.KEYPAD_PERCENT: KEYBOARD_HID_USAGE.KEYPAD_PERCENT,
    KEY_ID.KEYPAD_LESS: KEYBOARD_HID_USAGE.KEYPAD_LESS,
    KEY_ID.KEYPAD_MORE: KEYBOARD_HID_USAGE.KEYPAD_MORE,
    KEY_ID.KEYPAD_AMPERSAND: KEYBOARD_HID_USAGE.KEYPAD_AMPERSAND,
    KEY_ID.KEYPAD_LOGICAL_AND: KEYBOARD_HID_USAGE.KEYPAD_LOGICAL_AND,
    KEY_ID.KEYPAD_VERTICAL_BAR: KEYBOARD_HID_USAGE.KEYPAD_VERTICAL_BAR,
    KEY_ID.KEYPAD_LOGICAL_OR: KEYBOARD_HID_USAGE.KEYPAD_LOGICAL_OR,
    KEY_ID.KEYPAD_COLON: KEYBOARD_HID_USAGE.KEYPAD_COLON,
    KEY_ID.KEYPAD_HASH: KEYBOARD_HID_USAGE.KEYPAD_HASH,
    KEY_ID.KEYPAD_SPACE: KEYBOARD_HID_USAGE.KEYPAD_SPACE,
    KEY_ID.KEYPAD_AT_SIGN: KEYBOARD_HID_USAGE.KEYPAD_AT_SIGN,
    KEY_ID.KEYPAD_EXCLAMATION_MARK: KEYBOARD_HID_USAGE.KEYPAD_EXCLAMATION_MARK,
    KEY_ID.KEYPAD_MEMORY_STORE: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_STORE,
    KEY_ID.KEYPAD_MEMORY_RECALL: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_RECALL,
    KEY_ID.KEYPAD_MEMORY_CLEAR: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_CLEAR,
    KEY_ID.KEYPAD_MEMORY_ADD: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_ADD,
    KEY_ID.KEYPAD_MEMORY_SUBSTRACT: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_SUBSTRACT,
    KEY_ID.KEYPAD_MEMORY_MULTIPLY: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_MULTIPLY,
    KEY_ID.KEYPAD_MEMORY_DIVIDE: KEYBOARD_HID_USAGE.KEYPAD_MEMORY_DIVIDE,
    KEY_ID.KEYPAD_PLUS_MINUS: KEYBOARD_HID_USAGE.KEYPAD_PLUS_MINUS,
    KEY_ID.KEYPAD_CLEAR: KEYBOARD_HID_USAGE.KEYPAD_CLEAR,
    KEY_ID.KEYPAD_CLEAR_ENTRY: KEYBOARD_HID_USAGE.KEYPAD_CLEAR_ENTRY,
    KEY_ID.KEYPAD_BINARY: KEYBOARD_HID_USAGE.KEYPAD_BINARY,
    KEY_ID.KEYPAD_OCTAL: KEYBOARD_HID_USAGE.KEYPAD_OCTAL,
    KEY_ID.KEYPAD_DECIMAL: KEYBOARD_HID_USAGE.KEYPAD_DECIMAL,
    KEY_ID.KEYPAD_HEXADECIMAL: KEYBOARD_HID_USAGE.KEYPAD_HEXADECIMAL,
    KEY_ID.KEYBOARD_RIGHT_WIN_OR_OPTION: KEYBOARD_HID_USAGE.KEYBOARD_RIGHT_GUI
}


# ----------------------------------------------------------------------------------------------------------------------
# Implementation
# ----------------------------------------------------------------------------------------------------------------------
def format_consumer_usage_to_report_entry(consumer_usage):
    """
    Convert a key from the consumer usage dictionary into an entry of hid report in the 3 bytes long format 0x0A XX XX

    :param consumer_usage: the name of a consumer usage
    :type consumer_usage: ``str``

    :return: HID report entry
    :rtype: ``HexList``
    """
    usage = ConsumerHidUsage.__dict__[consumer_usage]
    return HexList([0x0A] + to_endian_list(usage, 2, little_endian=True))
# end def format_consumer_usage_to_report_entry

# ----------------------------------------------------------------------------------------------------------------------
# END OF FILE
# ----------------------------------------------------------------------------------------------------------------------
