// -------------------------------------
// Pipeline Configuration Section
properties([
    parameters([
        string(name: 'PROJECT_NAME', defaultValue: 'turbot', description: 'firmware hex file name', ),
        string(name: 'BRANCH_NAME', defaultValue: 'mpm18_turbot', description: 'project branch name on goldenpass', ),
        string(name: 'SOC_NAME', defaultValue: 'GLUON', description: 'System on a Chip definition', ),
        string(name: 'TEST_CONFIG', defaultValue: 'GLUON/TURBOT/HEAD', description: 'PRODUCT pyTestBox test configuration', ),
    ]),
// End of Pipeline Configuration Section
// -------------------------------------
    pipelineTriggers([
        // Trigger on every update on master 
        gerrit(
            serverName: 'goldenpass',
            gerritProjects: [[
                compareType: 'PLAIN',
                pattern: "ccp_fw/${params.BRANCH_NAME}",
                branches: [[ compareType: 'PLAIN', pattern: 'master' ]],
                disableStrictForbiddenFileVerification: false
            ]],
            triggerOnEvents: [
                refUpdated(),
            ]
        )
    ]),
])

timestamps {

    node ('builder') {

        stage ('Build Job - Checkout') {
            checkout([$class: 'GitSCM',
                branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false,
                extensions: [[ $class: 'CleanCheckout'],
                    [$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: false,
                    recursiveSubmodules: true, reference: '', trackingSubmodules: false
                ]],
                submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'Jenkins user',
                    url: "ssh://Jenkins@goldenpass.logitech.com:29418/ccp_fw/${params.BRANCH_NAME}"
                ]]
            ])
        } // End of stage ('Build Job - Checkout')

        stage ('Build Job - Build') {
            echo "PROJECT_NAME = ${params.PROJECT_NAME}"
            sh "git clean -x -f"
            // Shell build step - Build production and test firmwares,
            //                    valid test dfu and phcs#1 v1.5 verification dfu files
            // Shell build step - Copy hard-coded Jenkins dfu key into dfu test key
            sh """
              cd gcc_eclipse
              make clean PROJECT=${params.PROJECT_NAME}
              make clean  PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=build_ci
              cd ../config
              cp priv_tstkey_jenkins.pem priv_tstkey.pem
              cd ../gcc_eclipse
              make -j8 PROJECT=${params.PROJECT_NAME}
              make -j8 PROJECT=${params.PROJECT_NAME} OUT_DIR_PFX=build_ci CI_BUILD=1 dfu_evt
            """
            archiveArtifacts allowEmptyArchive: false,
                             artifacts: """**gcc_eclipse/**/*.dfu,
                                           **gcc_eclipse/build_*/${params.PROJECT_NAME}.hex,
                                           **gcc_eclipse/build_ci_*/${params.PROJECT_NAME}*.elf,
                                           **/dfu_*_key.txt,
                                           **/priv_tstkey_jenkins.pem""",
                             caseSensitive: true,
                             defaultExcludes: true,
                             fingerprint: false,
                             onlyIfSuccessful: false
            // Clean workspace at build end
            cleanWs()
        } // End of stage ('Build Job - Build')
    } // End of node ('builder')

    node ('fw_check') {

        stage ('Firmwares Comparison Job - Checkout') {
            checkout([$class: 'GitSCM',
                branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanCheckout']], submoduleCfg: [],
                userRemoteConfigs: [[credentialsId: 'GithubProductsCIToken', url: "https://github.com/Logitech/py-test-box.git"]]
            ])
        } // End of stage ('Firmwares Comparison Job - Checkout')

        stage ('Firmwares Comparison Job - Build') {
            script {
                copyArtifacts(
                    filter: """**gcc_eclipse/build_*/${params.PROJECT_NAME}.hex,
                               **gcc_eclipse/build_ci_*/${params.PROJECT_NAME}*.elf""",
                    projectName: env.JOB_NAME,
                    fingerprintArtifacts: true,
                    selector: specific(env.BUILD_NUMBER),
                    target: 'PYTESTBOX/TESTS/DFU_FILES'
                )

                try {
                    // Shell Unit Test step - framework initialization
                    sh """
                      python3 PYTESTBOX/LIBS/PYSETUP/pyEnvChecker.py
                    """
                    // Shell Unit Test step - production vs test firmwares comparison
                    def path = 'PYTESTBOX/TESTS/DFU_FILES/gcc_eclipse/build_'
                    sh """
                      python3 PYTESTBOX/CICD/ciscripts/compare_hex.py  \
                          -f ${path}${params.PROJECT_NAME}/${params.PROJECT_NAME}.hex  \
                          -c ${path}ci_${params.PROJECT_NAME}/${params.PROJECT_NAME}.hex \
                          -b {path}ci_${params.PROJECT_NAME}_btldr/${params.PROJECT_NAME}_btldr.elf \
                          -e {path}ci_${params.PROJECT_NAME}_app/${params.PROJECT_NAME}_app.elf
                    """
                }
                finally {
                    try {
                        // Permission cleanup
                        sh "python3 PYTESTBOX/CICD/ciscripts/permissions_clean_up.py"
                    }
                    catch(all) {
                        echo 'Error cleaning up permissions'
                    }
                }
            }
        } // End of stage ('Firmwares Comparison Job - Build')
    } // End of node ('slave')

    node (label: "${params.PROJECT_NAME} && power_board_v3") {
        stage ('Test Execution Job - Checkout') {
            checkout(
                [$class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: scm.extensions + [[$class: 'CleanCheckout'],
                        [$class: 'SubmoduleOption',
                        disableSubmodules: false,
                        parentCredentials: true,
                        recursiveSubmodules: true,
                        reference: '',
                        trackingSubmodules: false
                    ]],
                    submoduleCfg: [],
                    userRemoteConfigs: [
                     [credentialsId: 'GithubProductsCIToken',
                      url: "https://github.com/Logitech/py-test-box.git"]
                    ]
                ]
            )
        } // End of stage ('Test Execution Job - Checkout')

        stage ('Test Execution Job - Build') {
            script {
                copyArtifacts(
                    filter: """**gcc_eclipse/**/*.dfu,
                               **gcc_eclipse/build_ci_*/${params.PROJECT_NAME}.hex,
                               **/${params.PROJECT_NAME}_app.elf,
                               **/dfu_${params.PROJECT_NAME}_key.txt,
                               **/priv_tstkey_jenkins.pem""",
                    projectName: env.JOB_NAME,
                    fingerprintArtifacts: true,
                    selector: specific(env.BUILD_NUMBER),
                    target: 'PYTESTBOX/TESTS/DFU_FILES',
                    flatten: true
                )

                try {
                      // Shell build step - framework initialization
                      sh """
                        python3 PYTESTBOX/LIBS/PYSETUP/pyEnvChecker.py
                      """
                      // Get Node Name
                      def node_name = "${NODE_NAME}"
                      clean_node_name = node_name.replaceAll("\\s","_")
                      echo "The Node Name is: ${clean_node_name}"
                      // Shell Integration Test step - voltage calibration
                      sh """
                        python3 PYTESTBOX/CICD/ciscripts/power_supply.py -i -g -c -e
                      """
                      // Shell Integration Test step - turn on power
                      sh """
                        python3 PYTESTBOX/CICD/ciscripts/power_supply.py -i -s True -v 1.5 -o
                      """
                      // Product settings path
                      def settings_path = "PYTESTBOX/TESTS/SETTINGS/PYTESTBOX/PRODUCT"
                      // Shell Integration Test step - firmware code loading
                      sh """
                        python3 PYTESTBOX/CICD/ciscripts/jlink.py -v \
                            -f PYTESTBOX/TESTS/DFU_FILES/${params.PROJECT_NAME}.hex  \
                            -p ${params.SOC_NAME}  \
                            -n ${settings_path}/${params.TEST_CONFIG}/nvs_${clean_node_name}.hex
                      """
                      // Shell Integration Test step - power supply GPIO cleanup
                      sh """
                        python3 PYTESTBOX/CICD/ciscripts/power_supply.py -e
                      """
                      timeout(time: 60, unit: 'MINUTES', activity: true) {
                        // Shell Integration Test step - tests execution
                        sh """
                          python3 PYTESTBOX/TESTS/main.py  \
                              --file=PYTESTBOX/TESTS/SETTINGS/testFilter.txt \
                              --variant=PRODUCT/${params.TEST_CONFIG} \
                              --product=PYTESTBOX \
                              --target=DEVICE \
                              --output=console,log,junit,jrl \
                              --level=Interface,Business,Functionality,ErrorHandling,Robustness,Security,Time-consuming
                        """
                      }
                }
                finally {
                    try {
                        // Permission cleanup
                        sh "python3 PYTESTBOX/CICD/ciscripts/permissions_clean_up.py"
                    }
                    catch(all) {
                        echo 'Error cleaning up permissions'
                    }
                }
            }
          // Save JUnit Results
          junit "**/LOCAL/**/${params.TEST_CONFIG}/**/*.xml"
          archiveArtifacts allowEmptyArchive: true, artifacts: "**/LOCAL/**/${params.TEST_CONFIG}/**/log/*.log", caseSensitive: true, defaultExcludes: true, fingerprint: false, onlyIfSuccessful: false
        } // End of stage ('Test Execution Job - Build')
    } // End of node (label: "${params.PROJECT_NAME}")
} // End of timestamps
