"""
:tool: this file is not generated by a tool but look like it to the linter
:package: module_tool_no_error
:brief: sample file without errors
:author: Sylvana Ieri <sieri@logitech.com>
:date: 2024/05/30
"""
