#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
:package: codegenerator.input.userinput
:brief: UserInput for the code generation
:author: Suresh Thiyagarajan <sthiyagarajan@logitech.com>
:date: 2021/05/24
"""


# ----------------------------------------------------------------------------------------------------------------------
# implementation
# ----------------------------------------------------------------------------------------------------------------------
class UserInput(object):
    """
    Define user defined inputs

    This file will be autogenerated from Google spreadsheet (using Test Design Document and Test Case Document)

    Refer the ../README.md file
    """
    ARGS_OBJECT_REFERENCE = None

    ENABLE_HIDDEN_FEATURES = False
    ACTIVATE_FEATURE_COMPLIANCE = False
    ACTIVATE_FEATURE_GOTTHARD = False
    ACTIVATE_FEATURE_MANUFACTURING = False

    NVS_BACKUP_RESTORE = None

    AUTHOR_EMAIL_ID = None
    AUTHOR_NAME = None

    DAY = None
    MONTH = None
    YEAR = None

    EVENT_LIST = None
    FUNCTION_LIST = None

    HIDPP_CATEGORY = None
    HIDPP_FEATURE_COMMENT = None
    HIDPP_FEATURE_ID = None
    HIDPP_FEATURE_NAME = None
    HIDPP_FEATURE_VERSION = None
    HIDPP_TYPE = None
    HIDPP_VERSION = None

    TEST_CASES_INFO_BUSINESS = []
    TEST_CASES_INFO_ERROR_HANDLING = []
    TEST_CASES_INFO_FUNCTIONALITY = []
    TEST_CASES_INFO_INTERFACE = []
    TEST_CASES_INFO_ROBUSTNESS = []
    TEST_CASES_INFO_SECURITY = []
    TEST_CASES_INFO_PERFORMANCE = []
    TEST_CASES_INFO_SETUP_SECTION = []
    TEST_CASES_INFO_TEARDOWN_SECTION = []
# end class UserInput

# ----------------------------------------------------------------------------------------------------------------------
# END OF FILE
# ----------------------------------------------------------------------------------------------------------------------
