#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
# Python Test Box
# ------------------------------------------------------------------------------
"""
@package pyhid.hidparser.usagepages.illumination

@brief  HID parser usage pages Lighting And Illumination class
        Built from hutrr84_-_lighting_and_illumination_page.pdf

@author christophe Roquebert

@date   2019/07/15
"""
# ------------------------------------------------------------------------------
# imports
# ------------------------------------------------------------------------------
from pyhid.hidparser.UsagePage import UsagePage, UsageType, Usage


# ------------------------------------------------------------------------------
# implementation
# ------------------------------------------------------------------------------
class Illumination(UsagePage):

    @classmethod
    def _get_usage_page_index(cls):
        return 0x59

    UNDEFINED = Usage(0x00, UsageType.CONTROL_ON_OFF)  # OOC
    LAMP_ARRAY = Usage(0x01, UsageType.COLLECTION_APPLICATION)  # CA
    LAMP_ARRAY_ATTRIBUTES_REPORT = Usage(0x02, UsageType.COLLECTION_LOGICAL)  # CL
    LAMP_COUNT = Usage(0x03, UsageType.DATA_STATIC_VALUE)  # SV/DV
    BOUNDING_BOX_WIDTH_IN_MICROMETERS = Usage(0x04, UsageType.DATA_STATIC_VALUE)  # SV
    BOUNDING_BOX_HEIGHT_IN_MICROMETERS = Usage(0x05, UsageType.DATA_STATIC_VALUE)  # SV
    BOUNDING_BOX_DEPTH_IN_MICROMETERS = Usage(0x06, UsageType.DATA_STATIC_VALUE)  # SV
    LAMP_ARRAY_KIND = Usage(0x07, UsageType.DATA_STATIC_VALUE)  # SV
    MIN_UPDATE_INTERVAL_IN_MICROSECONDS = Usage(0x08, UsageType.DATA_STATIC_VALUE)  # SV
    RESERVED_09 = Usage(0x09, UsageType.COLLECTION_APPLICATION)
    RESERVED_0A = Usage(0x0A, UsageType.COLLECTION_APPLICATION)
    RESERVED_0B = Usage(0x0B, UsageType.COLLECTION_APPLICATION)
    RESERVED_0C = Usage(0x0C, UsageType.COLLECTION_APPLICATION)
    RESERVED_0D = Usage(0x0D, UsageType.COLLECTION_APPLICATION)
    RESERVED_0E = Usage(0x0E, UsageType.COLLECTION_APPLICATION)
    RESERVED_0F = Usage(0x0F, UsageType.COLLECTION_APPLICATION)
    RESERVED_10 = Usage(0x10, UsageType.COLLECTION_APPLICATION)
    RESERVED_11 = Usage(0x11, UsageType.COLLECTION_APPLICATION)
    RESERVED_12 = Usage(0x12, UsageType.COLLECTION_APPLICATION)
    RESERVED_13 = Usage(0x13, UsageType.COLLECTION_APPLICATION)
    RESERVED_14 = Usage(0x14, UsageType.COLLECTION_APPLICATION)
    RESERVED_15 = Usage(0x15, UsageType.COLLECTION_APPLICATION)
    RESERVED_16 = Usage(0x16, UsageType.COLLECTION_APPLICATION)
    RESERVED_17 = Usage(0x17, UsageType.COLLECTION_APPLICATION)
    RESERVED_18 = Usage(0x18, UsageType.COLLECTION_APPLICATION)
    RESERVED_19 = Usage(0x19, UsageType.COLLECTION_APPLICATION)
    RESERVED_1A = Usage(0x1A, UsageType.COLLECTION_APPLICATION)
    RESERVED_1B = Usage(0x1B, UsageType.COLLECTION_APPLICATION)
    RESERVED_1C = Usage(0x1C, UsageType.COLLECTION_APPLICATION)
    RESERVED_1D = Usage(0x1D, UsageType.COLLECTION_APPLICATION)
    RESERVED_1E = Usage(0x1E, UsageType.COLLECTION_APPLICATION)
    RESERVED_1F = Usage(0x1F, UsageType.COLLECTION_APPLICATION)
    LAMP_ATTRIBUTES_REQUEST_REPORT = Usage(0x20, UsageType.COLLECTION_LOGICAL)  # CL
    LAMP_ID = Usage(0x21, UsageType.DATA_STATIC_VALUE)  # SV/DV
    LAMP_ATTRIBUTES_RESPONSE_REPORT = Usage(0x22, UsageType.COLLECTION_LOGICAL)  # CL
    POSITION_X_IN_MICROMETERS = Usage(0x23, UsageType.DATA_DYNAMIC_VALUE)  # DV
    POSITION_Y_IN_MICROMETERS = Usage(0x24, UsageType.DATA_DYNAMIC_VALUE)  # DV
    POSITION_Z_IN_MICROMETERS = Usage(0x25, UsageType.DATA_DYNAMIC_VALUE)  # DV
    LAMP_PURPOSES = Usage(0x26, UsageType.DATA_DYNAMIC_VALUE)  # DV
    UPDATE_LATENCY_IN_MICROSECONDS = Usage(0x27, UsageType.DATA_DYNAMIC_VALUE)  # DV
    RED_LEVEL_COUNT = Usage(0x28, UsageType.DATA_DYNAMIC_VALUE)  # DV
    GREEN_LEVEL_COUNT = Usage(0x29, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BLUE_LEVEL_COUNT = Usage(0x2A, UsageType.DATA_DYNAMIC_VALUE)  # DV
    INTENSITY_LEVEL_COUNT = Usage(0x2B, UsageType.DATA_DYNAMIC_VALUE)  # DV
    IS_PROGRAMMABLE = Usage(0x2C, UsageType.DATA_DYNAMIC_VALUE)  # DV
    INPUT_BINDING = Usage(0x2D, UsageType.DATA_DYNAMIC_VALUE)  # DV
    RESERVED_2E = Usage(0x2E, UsageType.COLLECTION_APPLICATION)
    RESERVED_2F = Usage(0x2F, UsageType.COLLECTION_APPLICATION)
    RESERVED_30 = Usage(0x30, UsageType.COLLECTION_APPLICATION)
    RESERVED_31 = Usage(0x31, UsageType.COLLECTION_APPLICATION)
    RESERVED_32 = Usage(0x32, UsageType.COLLECTION_APPLICATION)
    RESERVED_33 = Usage(0x33, UsageType.COLLECTION_APPLICATION)
    RESERVED_34 = Usage(0x34, UsageType.COLLECTION_APPLICATION)
    RESERVED_35 = Usage(0x35, UsageType.COLLECTION_APPLICATION)
    RESERVED_36 = Usage(0x36, UsageType.COLLECTION_APPLICATION)
    RESERVED_37 = Usage(0x37, UsageType.COLLECTION_APPLICATION)
    RESERVED_38 = Usage(0x38, UsageType.COLLECTION_APPLICATION)
    RESERVED_39 = Usage(0x39, UsageType.COLLECTION_APPLICATION)
    RESERVED_3A = Usage(0x3A, UsageType.COLLECTION_APPLICATION)
    RESERVED_3B = Usage(0x3B, UsageType.COLLECTION_APPLICATION)
    RESERVED_3C = Usage(0x3C, UsageType.COLLECTION_APPLICATION)
    RESERVED_3D = Usage(0x3D, UsageType.COLLECTION_APPLICATION)
    RESERVED_3E = Usage(0x3E, UsageType.COLLECTION_APPLICATION)
    RESERVED_3F = Usage(0x3F, UsageType.COLLECTION_APPLICATION)
    RESERVED_40 = Usage(0x40, UsageType.COLLECTION_APPLICATION)
    RESERVED_41 = Usage(0x41, UsageType.COLLECTION_APPLICATION)
    RESERVED_42 = Usage(0x42, UsageType.COLLECTION_APPLICATION)
    RESERVED_43 = Usage(0x43, UsageType.COLLECTION_APPLICATION)
    RESERVED_44 = Usage(0x44, UsageType.COLLECTION_APPLICATION)
    RESERVED_45 = Usage(0x45, UsageType.COLLECTION_APPLICATION)
    RESERVED_46 = Usage(0x46, UsageType.COLLECTION_APPLICATION)
    RESERVED_47 = Usage(0x47, UsageType.COLLECTION_APPLICATION)
    RESERVED_48 = Usage(0x48, UsageType.COLLECTION_APPLICATION)
    RESERVED_49 = Usage(0x49, UsageType.COLLECTION_APPLICATION)
    RESERVED_4A = Usage(0x4A, UsageType.COLLECTION_APPLICATION)
    RESERVED_4B = Usage(0x4B, UsageType.COLLECTION_APPLICATION)
    RESERVED_4C = Usage(0x4C, UsageType.COLLECTION_APPLICATION)
    RESERVED_4D = Usage(0x4D, UsageType.COLLECTION_APPLICATION)
    RESERVED_4E = Usage(0x4E, UsageType.COLLECTION_APPLICATION)
    RESERVED_4F = Usage(0x4F, UsageType.COLLECTION_APPLICATION)
    LAMP_MULTI_UPDATE_REPORT = Usage(0x50, UsageType.COLLECTION_LOGICAL)  # CL
    RED_UPDATE_CHANNEL = Usage(0x51, UsageType.DATA_DYNAMIC_VALUE)  # DV
    GREEN_UPDATE_CHANNEL = Usage(0x52, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BLUE_UPDATE_CHANNEL = Usage(0x53, UsageType.DATA_DYNAMIC_VALUE)  # DV
    INTENSITY_UPDATE_CHANNEL = Usage(0x54, UsageType.DATA_DYNAMIC_VALUE)  # DV
    LAMP_UPDATE_FLAGS = Usage(0x55, UsageType.DATA_DYNAMIC_VALUE)  # DV
    RESERVED_56 = Usage(0x56, UsageType.COLLECTION_APPLICATION)
    RESERVED_57 = Usage(0x57, UsageType.COLLECTION_APPLICATION)
    RESERVED_58 = Usage(0x58, UsageType.COLLECTION_APPLICATION)
    RESERVED_59 = Usage(0x59, UsageType.COLLECTION_APPLICATION)
    RESERVED_5A = Usage(0x5A, UsageType.COLLECTION_APPLICATION)
    RESERVED_5B = Usage(0x5B, UsageType.COLLECTION_APPLICATION)
    RESERVED_5C = Usage(0x5C, UsageType.COLLECTION_APPLICATION)
    RESERVED_5D = Usage(0x5D, UsageType.COLLECTION_APPLICATION)
    RESERVED_5E = Usage(0x5E, UsageType.COLLECTION_APPLICATION)
    RESERVED_5F = Usage(0x5F, UsageType.COLLECTION_APPLICATION)
    LAMP_RANGE_UPDATE_REPORT = Usage(0x60, UsageType.COLLECTION_LOGICAL)  # CL
    LAMP_ID_START = Usage(0x61, UsageType.DATA_DYNAMIC_VALUE)  # DV
    LAMP_ID_END = Usage(0x62, UsageType.DATA_DYNAMIC_VALUE)  # DV
    RESERVED_63 = Usage(0x63, UsageType.COLLECTION_APPLICATION)
    RESERVED_64 = Usage(0x64, UsageType.COLLECTION_APPLICATION)
    RESERVED_65 = Usage(0x65, UsageType.COLLECTION_APPLICATION)
    RESERVED_66 = Usage(0x66, UsageType.COLLECTION_APPLICATION)
    RESERVED_67 = Usage(0x67, UsageType.COLLECTION_APPLICATION)
    RESERVED_68 = Usage(0x68, UsageType.COLLECTION_APPLICATION)
    RESERVED_69 = Usage(0x69, UsageType.COLLECTION_APPLICATION)
    RESERVED_6A = Usage(0x6A, UsageType.COLLECTION_APPLICATION)
    RESERVED_6B = Usage(0x6B, UsageType.COLLECTION_APPLICATION)
    RESERVED_6C = Usage(0x6C, UsageType.COLLECTION_APPLICATION)
    RESERVED_6D = Usage(0x6D, UsageType.COLLECTION_APPLICATION)
    RESERVED_6E = Usage(0x6E, UsageType.COLLECTION_APPLICATION)
    RESERVED_6F = Usage(0x6F, UsageType.COLLECTION_APPLICATION)
    LAMP_ARRAY_CONTROL_REPORT = Usage(0x70, UsageType.COLLECTION_LOGICAL)  # CL
    AUTONOMOUS_MODE = Usage(0x71, UsageType.DATA_DYNAMIC_VALUE)  # DV
    # 0x72-FFFF Reserved
    RESERVED_72 = Usage(0x72, UsageType.COLLECTION_APPLICATION)

# end class Illumination
