#!/usr/bin/env python
# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
# Python Test Box
# ------------------------------------------------------------------------------
"""
@package pyhid.hidparser.usagepages.simulationcontrol

@brief  HID parser usage pages simulation control class
        Built from https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf

@author christophe Roquebert

@date   2019/01/24
"""
# ------------------------------------------------------------------------------
# imports
# ------------------------------------------------------------------------------
from pyhid.hidparser.UsagePage import UsagePage, Usage, UsageType

# ------------------------------------------------------------------------------
# implementation
# ------------------------------------------------------------------------------


class SimulationControls(UsagePage):

    @classmethod
    def _get_usage_page_index(cls):
        """
        @return  Simulation Controls Page 0x02
        """
        return 0x02
    # end def _get_usage_page_index

    UNDEFINED = Usage(0x00, UsageType.COLLECTION_APPLICATION)  # CA
    FLIGHT_SIMULATION_DEVICE = Usage(0x01, UsageType.COLLECTION_APPLICATION)  # CA
    AUTOMOBILE_SIMULATION_DEVICE = Usage(0x02, UsageType.COLLECTION_APPLICATION)  # CA
    TANK_SIMULATION_DEVICE = Usage(0x03, UsageType.COLLECTION_APPLICATION)  # CA
    SPACESHIP_SIMULATION_DEVICE = Usage(0x04, UsageType.COLLECTION_APPLICATION)  # CA
    SUBMARINE_SIMULATION_DEVICE = Usage(0x05, UsageType.COLLECTION_APPLICATION)  # CA
    SAILING_SIMULATION_DEVICE = Usage(0x06, UsageType.COLLECTION_APPLICATION)  # CA
    MOTORCYCLE_SIMULATION_DEVICE = Usage(0x07, UsageType.COLLECTION_APPLICATION)  # CA
    SPORTS_SIMULATION_DEVICE = Usage(0x08, UsageType.COLLECTION_APPLICATION)  # CA
    AIRPLANE_SIMULATION_DEVICE = Usage(0x09, UsageType.COLLECTION_APPLICATION)  # CA
    HELICOPTER_SIMULATION_DEVICE = Usage(0x0A, UsageType.COLLECTION_APPLICATION)  # CA
    MAGIC_CARPET_SIMULATION_DEVICE = Usage(0x0B, UsageType.COLLECTION_APPLICATION)  # CA
    BICYCLE = Usage(0x0C, UsageType.COLLECTION_APPLICATION)  # CA
    RESERVED_0D = Usage(0x0D, UsageType.COLLECTION_APPLICATION)
    RESERVED_0E = Usage(0x0E, UsageType.COLLECTION_APPLICATION)
    RESERVED_0F = Usage(0x0F, UsageType.COLLECTION_APPLICATION)
    RESERVED_10 = Usage(0x10, UsageType.COLLECTION_APPLICATION)
    RESERVED_11 = Usage(0x11, UsageType.COLLECTION_APPLICATION)
    RESERVED_12 = Usage(0x12, UsageType.COLLECTION_APPLICATION)
    RESERVED_13 = Usage(0x13, UsageType.COLLECTION_APPLICATION)
    RESERVED_14 = Usage(0x14, UsageType.COLLECTION_APPLICATION)
    RESERVED_15 = Usage(0x15, UsageType.COLLECTION_APPLICATION)
    RESERVED_16 = Usage(0x16, UsageType.COLLECTION_APPLICATION)
    RESERVED_17 = Usage(0x17, UsageType.COLLECTION_APPLICATION)
    RESERVED_18 = Usage(0x18, UsageType.COLLECTION_APPLICATION)
    RESERVED_19 = Usage(0x19, UsageType.COLLECTION_APPLICATION)
    RESERVED_1A = Usage(0x1A, UsageType.COLLECTION_APPLICATION)
    RESERVED_1B = Usage(0x1B, UsageType.COLLECTION_APPLICATION)
    RESERVED_1C = Usage(0x1C, UsageType.COLLECTION_APPLICATION)
    RESERVED_1D = Usage(0x1D, UsageType.COLLECTION_APPLICATION)
    RESERVED_1E = Usage(0x1E, UsageType.COLLECTION_APPLICATION)
    RESERVED_1F = Usage(0x1F, UsageType.COLLECTION_APPLICATION)
    FLIGHT_CONTROL_STICK = Usage(0x20, UsageType.COLLECTION_APPLICATION)  # CA
    FLIGHT_STICK = Usage(0x21, UsageType.COLLECTION_APPLICATION)  # CA
    CYCLIC_CONTROL = Usage(0x22, UsageType.COLLECTION_PHYSICAL)  # CP
    CYCLIC_TRIM = Usage(0x23, UsageType.COLLECTION_PHYSICAL)  # CP
    FLIGHT_YOKE = Usage(0x24, UsageType.COLLECTION_APPLICATION)  # CA
    TRACK_CONTROL = Usage(0x25, UsageType.COLLECTION_PHYSICAL)  # CP
    DRIVING_CONTROL = Usage(0x26, UsageType.COLLECTION_APPLICATION)  # CA
    RESERVED_27 = Usage(0x27, UsageType.COLLECTION_APPLICATION)
    RESERVED_28 = Usage(0x28, UsageType.COLLECTION_APPLICATION)
    RESERVED_29 = Usage(0x29, UsageType.COLLECTION_APPLICATION)
    RESERVED_2A = Usage(0x2A, UsageType.COLLECTION_APPLICATION)
    RESERVED_2B = Usage(0x2B, UsageType.COLLECTION_APPLICATION)
    RESERVED_2C = Usage(0x2C, UsageType.COLLECTION_APPLICATION)
    RESERVED_2D = Usage(0x2D, UsageType.COLLECTION_APPLICATION)
    RESERVED_2E = Usage(0x2E, UsageType.COLLECTION_APPLICATION)
    RESERVED_2F = Usage(0x2F, UsageType.COLLECTION_APPLICATION)
    RESERVED_30 = Usage(0x30, UsageType.COLLECTION_APPLICATION)
    RESERVED_31 = Usage(0x31, UsageType.COLLECTION_APPLICATION)
    RESERVED_32 = Usage(0x32, UsageType.COLLECTION_APPLICATION)
    RESERVED_33 = Usage(0x33, UsageType.COLLECTION_APPLICATION)
    RESERVED_34 = Usage(0x34, UsageType.COLLECTION_APPLICATION)
    RESERVED_35 = Usage(0x35, UsageType.COLLECTION_APPLICATION)
    RESERVED_36 = Usage(0x36, UsageType.COLLECTION_APPLICATION)
    RESERVED_37 = Usage(0x37, UsageType.COLLECTION_APPLICATION)
    RESERVED_38 = Usage(0x38, UsageType.COLLECTION_APPLICATION)
    RESERVED_39 = Usage(0x39, UsageType.COLLECTION_APPLICATION)
    RESERVED_3A = Usage(0x3A, UsageType.COLLECTION_APPLICATION)
    RESERVED_3B = Usage(0x3B, UsageType.COLLECTION_APPLICATION)
    RESERVED_3C = Usage(0x3C, UsageType.COLLECTION_APPLICATION)
    RESERVED_3D = Usage(0x3D, UsageType.COLLECTION_APPLICATION)
    RESERVED_3E = Usage(0x3E, UsageType.COLLECTION_APPLICATION)
    RESERVED_3F = Usage(0x3F, UsageType.COLLECTION_APPLICATION)
    RESERVED_40 = Usage(0x40, UsageType.COLLECTION_APPLICATION)
    RESERVED_41 = Usage(0x41, UsageType.COLLECTION_APPLICATION)
    RESERVED_42 = Usage(0x42, UsageType.COLLECTION_APPLICATION)
    RESERVED_43 = Usage(0x43, UsageType.COLLECTION_APPLICATION)
    RESERVED_44 = Usage(0x44, UsageType.COLLECTION_APPLICATION)
    RESERVED_45 = Usage(0x45, UsageType.COLLECTION_APPLICATION)
    RESERVED_46 = Usage(0x46, UsageType.COLLECTION_APPLICATION)
    RESERVED_47 = Usage(0x47, UsageType.COLLECTION_APPLICATION)
    RESERVED_48 = Usage(0x48, UsageType.COLLECTION_APPLICATION)
    RESERVED_49 = Usage(0x49, UsageType.COLLECTION_APPLICATION)
    RESERVED_4A = Usage(0x4A, UsageType.COLLECTION_APPLICATION)
    RESERVED_4B = Usage(0x4B, UsageType.COLLECTION_APPLICATION)
    RESERVED_4C = Usage(0x4C, UsageType.COLLECTION_APPLICATION)
    RESERVED_4D = Usage(0x4D, UsageType.COLLECTION_APPLICATION)
    RESERVED_4E = Usage(0x4E, UsageType.COLLECTION_APPLICATION)
    RESERVED_4F = Usage(0x4F, UsageType.COLLECTION_APPLICATION)
    RESERVED_50 = Usage(0x50, UsageType.COLLECTION_APPLICATION)
    RESERVED_51 = Usage(0x51, UsageType.COLLECTION_APPLICATION)
    RESERVED_52 = Usage(0x52, UsageType.COLLECTION_APPLICATION)
    RESERVED_53 = Usage(0x53, UsageType.COLLECTION_APPLICATION)
    RESERVED_54 = Usage(0x54, UsageType.COLLECTION_APPLICATION)
    RESERVED_55 = Usage(0x55, UsageType.COLLECTION_APPLICATION)
    RESERVED_56 = Usage(0x56, UsageType.COLLECTION_APPLICATION)
    RESERVED_57 = Usage(0x57, UsageType.COLLECTION_APPLICATION)
    RESERVED_58 = Usage(0x58, UsageType.COLLECTION_APPLICATION)
    RESERVED_59 = Usage(0x59, UsageType.COLLECTION_APPLICATION)
    RESERVED_5A = Usage(0x5A, UsageType.COLLECTION_APPLICATION)
    RESERVED_5B = Usage(0x5B, UsageType.COLLECTION_APPLICATION)
    RESERVED_5C = Usage(0x5C, UsageType.COLLECTION_APPLICATION)
    RESERVED_5D = Usage(0x5D, UsageType.COLLECTION_APPLICATION)
    RESERVED_5E = Usage(0x5E, UsageType.COLLECTION_APPLICATION)
    RESERVED_5F = Usage(0x5F, UsageType.COLLECTION_APPLICATION)
    RESERVED_60 = Usage(0x60, UsageType.COLLECTION_APPLICATION)
    RESERVED_61 = Usage(0x61, UsageType.COLLECTION_APPLICATION)
    RESERVED_62 = Usage(0x62, UsageType.COLLECTION_APPLICATION)
    RESERVED_63 = Usage(0x63, UsageType.COLLECTION_APPLICATION)
    RESERVED_64 = Usage(0x64, UsageType.COLLECTION_APPLICATION)
    RESERVED_65 = Usage(0x65, UsageType.COLLECTION_APPLICATION)
    RESERVED_66 = Usage(0x66, UsageType.COLLECTION_APPLICATION)
    RESERVED_67 = Usage(0x67, UsageType.COLLECTION_APPLICATION)
    RESERVED_68 = Usage(0x68, UsageType.COLLECTION_APPLICATION)
    RESERVED_69 = Usage(0x69, UsageType.COLLECTION_APPLICATION)
    RESERVED_6A = Usage(0x6A, UsageType.COLLECTION_APPLICATION)
    RESERVED_6B = Usage(0x6B, UsageType.COLLECTION_APPLICATION)
    RESERVED_6C = Usage(0x6C, UsageType.COLLECTION_APPLICATION)
    RESERVED_6D = Usage(0x6D, UsageType.COLLECTION_APPLICATION)
    RESERVED_6E = Usage(0x6E, UsageType.COLLECTION_APPLICATION)
    RESERVED_6F = Usage(0x6F, UsageType.COLLECTION_APPLICATION)
    RESERVED_70 = Usage(0x70, UsageType.COLLECTION_APPLICATION)
    RESERVED_71 = Usage(0x71, UsageType.COLLECTION_APPLICATION)
    RESERVED_72 = Usage(0x72, UsageType.COLLECTION_APPLICATION)
    RESERVED_73 = Usage(0x73, UsageType.COLLECTION_APPLICATION)
    RESERVED_74 = Usage(0x74, UsageType.COLLECTION_APPLICATION)
    RESERVED_75 = Usage(0x75, UsageType.COLLECTION_APPLICATION)
    RESERVED_76 = Usage(0x76, UsageType.COLLECTION_APPLICATION)
    RESERVED_77 = Usage(0x77, UsageType.COLLECTION_APPLICATION)
    RESERVED_78 = Usage(0x78, UsageType.COLLECTION_APPLICATION)
    RESERVED_79 = Usage(0x79, UsageType.COLLECTION_APPLICATION)
    RESERVED_7A = Usage(0x7A, UsageType.COLLECTION_APPLICATION)
    RESERVED_7B = Usage(0x7B, UsageType.COLLECTION_APPLICATION)
    RESERVED_7C = Usage(0x7C, UsageType.COLLECTION_APPLICATION)
    RESERVED_7D = Usage(0x7D, UsageType.COLLECTION_APPLICATION)
    RESERVED_7E = Usage(0x7E, UsageType.COLLECTION_APPLICATION)
    RESERVED_7F = Usage(0x7F, UsageType.COLLECTION_APPLICATION)
    RESERVED_80 = Usage(0x80, UsageType.COLLECTION_APPLICATION)
    RESERVED_81 = Usage(0x81, UsageType.COLLECTION_APPLICATION)
    RESERVED_82 = Usage(0x82, UsageType.COLLECTION_APPLICATION)
    RESERVED_83 = Usage(0x83, UsageType.COLLECTION_APPLICATION)
    RESERVED_84 = Usage(0x84, UsageType.COLLECTION_APPLICATION)
    RESERVED_85 = Usage(0x85, UsageType.COLLECTION_APPLICATION)
    RESERVED_86 = Usage(0x86, UsageType.COLLECTION_APPLICATION)
    RESERVED_87 = Usage(0x87, UsageType.COLLECTION_APPLICATION)
    RESERVED_88 = Usage(0x88, UsageType.COLLECTION_APPLICATION)
    RESERVED_89 = Usage(0x89, UsageType.COLLECTION_APPLICATION)
    RESERVED_8A = Usage(0x8A, UsageType.COLLECTION_APPLICATION)
    RESERVED_8B = Usage(0x8B, UsageType.COLLECTION_APPLICATION)
    RESERVED_8C = Usage(0x8C, UsageType.COLLECTION_APPLICATION)
    RESERVED_8D = Usage(0x8D, UsageType.COLLECTION_APPLICATION)
    RESERVED_8E = Usage(0x8E, UsageType.COLLECTION_APPLICATION)
    RESERVED_8F = Usage(0x8F, UsageType.COLLECTION_APPLICATION)
    RESERVED_90 = Usage(0x90, UsageType.COLLECTION_APPLICATION)
    RESERVED_91 = Usage(0x91, UsageType.COLLECTION_APPLICATION)
    RESERVED_92 = Usage(0x92, UsageType.COLLECTION_APPLICATION)
    RESERVED_93 = Usage(0x93, UsageType.COLLECTION_APPLICATION)
    RESERVED_94 = Usage(0x94, UsageType.COLLECTION_APPLICATION)
    RESERVED_95 = Usage(0x95, UsageType.COLLECTION_APPLICATION)
    RESERVED_96 = Usage(0x96, UsageType.COLLECTION_APPLICATION)
    RESERVED_97 = Usage(0x97, UsageType.COLLECTION_APPLICATION)
    RESERVED_98 = Usage(0x98, UsageType.COLLECTION_APPLICATION)
    RESERVED_99 = Usage(0x99, UsageType.COLLECTION_APPLICATION)
    RESERVED_9A = Usage(0x9A, UsageType.COLLECTION_APPLICATION)
    RESERVED_9B = Usage(0x9B, UsageType.COLLECTION_APPLICATION)
    RESERVED_9C = Usage(0x9C, UsageType.COLLECTION_APPLICATION)
    RESERVED_9D = Usage(0x9D, UsageType.COLLECTION_APPLICATION)
    RESERVED_9E = Usage(0x9E, UsageType.COLLECTION_APPLICATION)
    RESERVED_9F = Usage(0x9F, UsageType.COLLECTION_APPLICATION)
    RESERVED_A0 = Usage(0xA0, UsageType.COLLECTION_APPLICATION)
    RESERVED_A1 = Usage(0xA1, UsageType.COLLECTION_APPLICATION)
    RESERVED_A2 = Usage(0xA2, UsageType.COLLECTION_APPLICATION)
    RESERVED_A3 = Usage(0xA3, UsageType.COLLECTION_APPLICATION)
    RESERVED_A4 = Usage(0xA4, UsageType.COLLECTION_APPLICATION)
    RESERVED_A5 = Usage(0xA5, UsageType.COLLECTION_APPLICATION)
    RESERVED_A6 = Usage(0xA6, UsageType.COLLECTION_APPLICATION)
    RESERVED_A7 = Usage(0xA7, UsageType.COLLECTION_APPLICATION)
    RESERVED_A8 = Usage(0xA8, UsageType.COLLECTION_APPLICATION)
    RESERVED_A9 = Usage(0xA9, UsageType.COLLECTION_APPLICATION)
    RESERVED_AA = Usage(0xAA, UsageType.COLLECTION_APPLICATION)
    RESERVED_AB = Usage(0xAB, UsageType.COLLECTION_APPLICATION)
    RESERVED_AC = Usage(0xAC, UsageType.COLLECTION_APPLICATION)
    RESERVED_AD = Usage(0xAD, UsageType.COLLECTION_APPLICATION)
    RESERVED_AE = Usage(0xAE, UsageType.COLLECTION_APPLICATION)
    RESERVED_AF = Usage(0xAF, UsageType.COLLECTION_APPLICATION)
    AILERON = Usage(0xB0, UsageType.DATA_DYNAMIC_VALUE)  # DV
    AILERON_TRIM = Usage(0xB1, UsageType.DATA_DYNAMIC_VALUE)  # DV
    ANTI_TORQUE_CONTROL = Usage(0xB2, UsageType.DATA_DYNAMIC_VALUE)  # DV
    AUTO_PILOT_ENABLE = Usage(0xB3, UsageType.CONTROL_ON_OFF)  # OOC
    CHAFF_RELEASE = Usage(0xB4, UsageType.CONTROL_ONE_SHOT)  # OSC
    COLLECTIVE_CONTROL = Usage(0xB5, UsageType.DATA_DYNAMIC_VALUE)  # DV
    DIVE_BRAKE = Usage(0xB6, UsageType.DATA_DYNAMIC_VALUE)  # DV
    ELECTRONIC_COUNTER_MEASURES = Usage(0xB7, UsageType.CONTROL_ON_OFF)  # OOC
    ELEVATOR = Usage(0xB8, UsageType.DATA_DYNAMIC_VALUE)  # DV
    ELEVATOR_TRIM = Usage(0xB9, UsageType.DATA_DYNAMIC_VALUE)  # DV
    RUDDER = Usage(0xBA, UsageType.DATA_DYNAMIC_VALUE)  # DV
    THROTTLE = Usage(0xBB, UsageType.DATA_DYNAMIC_VALUE)  # DV
    FLIGHT_COMMUNICATION = Usage(0xBC, UsageType.CONTROL_ON_OFF)  # OOC
    FLARE_RELEASE = Usage(0xBD, UsageType.CONTROL_ONE_SHOT)  # OSC
    LANDING_GEAR = Usage(0xBE, UsageType.CONTROL_ON_OFF)  # OOC
    TOE_BRAKE = Usage(0xBF, UsageType.DATA_DYNAMIC_VALUE)  # DV
    TRIGGER = Usage(0xC0, UsageType.CONTROL_MOMENTARY)  # MC
    WEAPONS_ARM = Usage(0xC1, UsageType.CONTROL_ON_OFF)  # OOC
    WEAPONS_SELECT = Usage(0xC2, UsageType.CONTROL_ONE_SHOT)  # OSC
    WING_FLAPS = Usage(0xC3, UsageType.DATA_DYNAMIC_VALUE)  # DV
    ACCELERATOR = Usage(0xC4, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BRAKE = Usage(0xC5, UsageType.DATA_DYNAMIC_VALUE)  # DV
    CLUTCH = Usage(0xC6, UsageType.DATA_DYNAMIC_VALUE)  # DV
    SHIFTER = Usage(0xC7, UsageType.DATA_DYNAMIC_VALUE)  # DV
    STEERING = Usage(0xC8, UsageType.DATA_DYNAMIC_VALUE)  # DV
    TURRET_DIRECTION = Usage(0xC9, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BARREL_ELEVATION = Usage(0xCA, UsageType.DATA_DYNAMIC_VALUE)  # DV
    DIVE_PLANE = Usage(0xCB, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BALLAST = Usage(0xCC, UsageType.DATA_DYNAMIC_VALUE)  # DV
    BICYCLE_CRANK = Usage(0xCD, UsageType.DATA_DYNAMIC_VALUE)  # DV
    HANDLE_BARS = Usage(0xCE, UsageType.DATA_DYNAMIC_VALUE)  # DV
    FRONT_BRAKE = Usage(0xCF, UsageType.DATA_DYNAMIC_VALUE)  # DV
    REAR_BRAKE = Usage(0xD0, UsageType.DATA_DYNAMIC_VALUE)  # DV

# end class SimulationControls
